<?php

/**
 * PaymentDisputesApi
 * PHP version 8.1
 *
 * @category Class
 * @package  PAYJPV2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PAY.JP API v2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PAYJPV2\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use PAYJPV2\ApiException;
use PAYJPV2\Configuration;
use PAYJPV2\HeaderSelector;
use PAYJPV2\ObjectSerializer;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;

/**
 * PaymentDisputesApi Class Doc Comment
 *
 * @category Class
 * @package  PAYJPV2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PaymentDisputesApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] * */
    public const contentTypes = [
        'getAllPaymentDisputes' => [
            'application/json',
        ],
        'getPaymentDispute' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getAllPaymentDisputes
     *
     * Get All Payment Disputes
     *
     * @param  int|null $limit 取得するデータの最大件数 (optional, default to 10)
     * @param  string|null $startingAfter このIDより後のデータを取得 (optional)
     * @param  string|null $endingBefore このIDより前のデータを取得 (optional)
     * @param  string|null $paymentFlowId 取得する payment_dispute に紐づく payment_flow の ID (optional)
     * @param  \PAYJPV2\Model\PaymentDisputeStatus[]|null $status 取得する payment_dispute のステータス。複数指定可能 (optional)
     * @param  string|null $idempotencyKey Idempotency key for the request
     *
     * @throws \PAYJPV2\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \PAYJPV2\Model\PaymentDisputeListResponse|\PAYJPV2\Model\ErrorResponse|\PAYJPV2\Model\ErrorResponse
     */
    public function getAllPaymentDisputes($limit = 10, $startingAfter = null, $endingBefore = null, $paymentFlowId = null, $status = null, ?string $idempotencyKey = null)
    {
        list($response) = $this->getAllPaymentDisputesWithHttpInfo($limit, $startingAfter, $endingBefore, $paymentFlowId, $status, $idempotencyKey);

        return $response;
    }

    /**
     * Operation getAllPaymentDisputesWithHttpInfo
     *
     * Get All Payment Disputes
     *
     * @param  int|null $limit 取得するデータの最大件数 (optional, default to 10)
     * @param  string|null $startingAfter このIDより後のデータを取得 (optional)
     * @param  string|null $endingBefore このIDより前のデータを取得 (optional)
     * @param  string|null $paymentFlowId 取得する payment_dispute に紐づく payment_flow の ID (optional)
     * @param  \PAYJPV2\Model\PaymentDisputeStatus[]|null $status 取得する payment_dispute のステータス。複数指定可能 (optional)
     * @param  string|null $idempotencyKey Idempotency key for the request
     *
     * @throws \PAYJPV2\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \PAYJPV2\Model\PaymentDisputeListResponse|\PAYJPV2\Model\ErrorResponse|\PAYJPV2\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getAllPaymentDisputesWithHttpInfo($limit = 10, $startingAfter = null, $endingBefore = null, $paymentFlowId = null, $status = null, ?string $idempotencyKey = null)
    {
        $request = $this->getAllPaymentDisputesRequest($limit, $startingAfter, $endingBefore, $paymentFlowId, $status, $idempotencyKey);

        try {
            $options = $this->createHttpClientOption();

            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch ($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\PAYJPV2\Model\PaymentDisputeListResponse',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\PAYJPV2\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\PAYJPV2\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }



            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\PAYJPV2\Model\PaymentDisputeListResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\PAYJPV2\Model\PaymentDisputeListResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);

                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\PAYJPV2\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);

                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\PAYJPV2\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);

                    throw $e;
            }


            throw $e;
        }
    }

    /**
     * Operation getAllPaymentDisputesAsync
     *
     * Get All Payment Disputes
     *
     * @param  int|null $limit 取得するデータの最大件数 (optional, default to 10)
     * @param  string|null $startingAfter このIDより後のデータを取得 (optional)
     * @param  string|null $endingBefore このIDより前のデータを取得 (optional)
     * @param  string|null $paymentFlowId 取得する payment_dispute に紐づく payment_flow の ID (optional)
     * @param  \PAYJPV2\Model\PaymentDisputeStatus[]|null $status 取得する payment_dispute のステータス。複数指定可能 (optional)
     * @param  string|null $idempotencyKey Idempotency key for the request
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAllPaymentDisputesAsync($limit = 10, $startingAfter = null, $endingBefore = null, $paymentFlowId = null, $status = null, ?string $idempotencyKey = null)
    {
        return $this->getAllPaymentDisputesAsyncWithHttpInfo($limit, $startingAfter, $endingBefore, $paymentFlowId, $status, $idempotencyKey)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getAllPaymentDisputesAsyncWithHttpInfo
     *
     * Get All Payment Disputes
     *
     * @param  int|null $limit 取得するデータの最大件数 (optional, default to 10)
     * @param  string|null $startingAfter このIDより後のデータを取得 (optional)
     * @param  string|null $endingBefore このIDより前のデータを取得 (optional)
     * @param  string|null $paymentFlowId 取得する payment_dispute に紐づく payment_flow の ID (optional)
     * @param  \PAYJPV2\Model\PaymentDisputeStatus[]|null $status 取得する payment_dispute のステータス。複数指定可能 (optional)
     * @param  string|null $idempotencyKey Idempotency key for the request
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAllPaymentDisputesAsyncWithHttpInfo($limit = 10, $startingAfter = null, $endingBefore = null, $paymentFlowId = null, $status = null, ?string $idempotencyKey = null)
    {
        $returnType = '\PAYJPV2\Model\PaymentDisputeListResponse';
        $request = $this->getAllPaymentDisputesRequest($limit, $startingAfter, $endingBefore, $paymentFlowId, $status, $idempotencyKey);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();

                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getAllPaymentDisputes'
     *
     * @param  int|null $limit 取得するデータの最大件数 (optional, default to 10)
     * @param  string|null $startingAfter このIDより後のデータを取得 (optional)
     * @param  string|null $endingBefore このIDより前のデータを取得 (optional)
     * @param  string|null $paymentFlowId 取得する payment_dispute に紐づく payment_flow の ID (optional)
     * @param  \PAYJPV2\Model\PaymentDisputeStatus[]|null $status 取得する payment_dispute のステータス。複数指定可能 (optional)
     * @param  string|null $idempotencyKey Idempotency key for the request
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getAllPaymentDisputesRequest($limit = 10, $startingAfter = null, $endingBefore = null, $paymentFlowId = null, $status = null, ?string $idempotencyKey = null)
    {

        if ($limit !== null && $limit > 100) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling PaymentDisputesApi.getAllPaymentDisputes, must be smaller than or equal to 100.');
        }
        if ($limit !== null && $limit < 1) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling PaymentDisputesApi.getAllPaymentDisputes, must be bigger than or equal to 1.');
        }






        $resourcePath = '/v2/payment_disputes';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // idempotency key
        if ($idempotencyKey !== null) {
            $headerParams['Idempotency-Key'] = $idempotencyKey;
        }

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $startingAfter,
            'starting_after', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $endingBefore,
            'ending_before', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $paymentFlowId,
            'payment_flow_id', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $status,
            'status', // param base name
            'array', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'application/problem+json', ],
            'application/json',
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem,
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (! empty($this->config->getUsername()) || ! (empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires Bearer authentication (access token)
        if (! empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        $defaultHeaders['X-Payjp-Client-User-Agent'] = Configuration::buildClientUserAgent();

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);

        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getPaymentDispute
     *
     * Get Payment Dispute
     *
     * @param  string $paymentDisputeId paymentDisputeId (required)
     * @param  string|null $idempotencyKey Idempotency key for the request
     *
     * @throws \PAYJPV2\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \PAYJPV2\Model\PaymentDisputeResponse|\PAYJPV2\Model\ErrorResponse|\PAYJPV2\Model\ErrorResponse
     */
    public function getPaymentDispute($paymentDisputeId, ?string $idempotencyKey = null)
    {
        list($response) = $this->getPaymentDisputeWithHttpInfo($paymentDisputeId, $idempotencyKey);

        return $response;
    }

    /**
     * Operation getPaymentDisputeWithHttpInfo
     *
     * Get Payment Dispute
     *
     * @param  string $paymentDisputeId (required)
     * @param  string|null $idempotencyKey Idempotency key for the request
     *
     * @throws \PAYJPV2\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \PAYJPV2\Model\PaymentDisputeResponse|\PAYJPV2\Model\ErrorResponse|\PAYJPV2\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getPaymentDisputeWithHttpInfo($paymentDisputeId, ?string $idempotencyKey = null)
    {
        $request = $this->getPaymentDisputeRequest($paymentDisputeId, $idempotencyKey);

        try {
            $options = $this->createHttpClientOption();

            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch ($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\PAYJPV2\Model\PaymentDisputeResponse',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\PAYJPV2\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\PAYJPV2\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }



            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\PAYJPV2\Model\PaymentDisputeResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\PAYJPV2\Model\PaymentDisputeResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);

                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\PAYJPV2\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);

                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\PAYJPV2\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);

                    throw $e;
            }


            throw $e;
        }
    }

    /**
     * Operation getPaymentDisputeAsync
     *
     * Get Payment Dispute
     *
     * @param  string $paymentDisputeId (required)
     * @param  string|null $idempotencyKey Idempotency key for the request
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getPaymentDisputeAsync($paymentDisputeId, ?string $idempotencyKey = null)
    {
        return $this->getPaymentDisputeAsyncWithHttpInfo($paymentDisputeId, $idempotencyKey)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getPaymentDisputeAsyncWithHttpInfo
     *
     * Get Payment Dispute
     *
     * @param  string $paymentDisputeId (required)
     * @param  string|null $idempotencyKey Idempotency key for the request
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getPaymentDisputeAsyncWithHttpInfo($paymentDisputeId, ?string $idempotencyKey = null)
    {
        $returnType = '\PAYJPV2\Model\PaymentDisputeResponse';
        $request = $this->getPaymentDisputeRequest($paymentDisputeId, $idempotencyKey);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();

                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getPaymentDispute'
     *
     * @param  string $paymentDisputeId (required)
     * @param  string|null $idempotencyKey Idempotency key for the request
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getPaymentDisputeRequest($paymentDisputeId, ?string $idempotencyKey = null)
    {

        // verify the required parameter 'paymentDisputeId' is set
        if ($paymentDisputeId === null || (is_array($paymentDisputeId) && count($paymentDisputeId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $paymentDisputeId when calling getPaymentDispute'
            );
        }


        $resourcePath = '/v2/payment_disputes/{payment_dispute_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // idempotency key
        if ($idempotencyKey !== null) {
            $headerParams['Idempotency-Key'] = $idempotencyKey;
        }



        // path params
        if ($paymentDisputeId !== null) {
            $resourcePath = str_replace(
                '{' . 'payment_dispute_id' . '}',
                ObjectSerializer::toPathValue($paymentDisputeId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'application/problem+json', ],
            'application/json',
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem,
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (! empty($this->config->getUsername()) || ! (empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires Bearer authentication (access token)
        if (! empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        $defaultHeaders['X-Payjp-Client-User-Agent'] = Configuration::buildClientUserAgent();

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);

        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (! $options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders(),
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
