<?php
/**
 * PaymentMethodConfigurationsApi
 * PHP version 8.1
 *
 * @category Class
 * @package  PAYJPV2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PAY.JP v2 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PAYJPV2\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use PAYJPV2\ApiException;
use PAYJPV2\Configuration;
use PAYJPV2\FormDataProcessor;
use PAYJPV2\HeaderSelector;
use PAYJPV2\ObjectSerializer;

/**
 * PaymentMethodConfigurationsApi Class Doc Comment
 *
 * @category Class
 * @package  PAYJPV2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PaymentMethodConfigurationsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getAllPaymentMethodConfigurations' => [
            'application/json',
        ],
        'getPaymentMethodConfiguration' => [
            'application/json',
        ],
        'updatePaymentMethodConfiguration' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getAllPaymentMethodConfigurations
     *
     * Get All Payment Method Configurations
     *
     * @param  int|null $limit 取得するデータの最大件数 (optional, default to 10)
     * @param  string|null $starting_after このIDより後のデータを取得 (optional)
     * @param  string|null $ending_before このIDより前のデータを取得 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAllPaymentMethodConfigurations'] to see the possible values for this operation
     *
     * @throws \PAYJPV2\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \PAYJPV2\Model\PaymentMethodConfigurationListResponse|\PAYJPV2\Model\ErrorResponse|\PAYJPV2\Model\ErrorResponse
     */
    public function getAllPaymentMethodConfigurations($limit = 10, $starting_after = null, $ending_before = null, string $contentType = self::contentTypes['getAllPaymentMethodConfigurations'][0])
    {
        list($response) = $this->getAllPaymentMethodConfigurationsWithHttpInfo($limit, $starting_after, $ending_before, $contentType);
        return $response;
    }

    /**
     * Operation getAllPaymentMethodConfigurationsWithHttpInfo
     *
     * Get All Payment Method Configurations
     *
     * @param  int|null $limit 取得するデータの最大件数 (optional, default to 10)
     * @param  string|null $starting_after このIDより後のデータを取得 (optional)
     * @param  string|null $ending_before このIDより前のデータを取得 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAllPaymentMethodConfigurations'] to see the possible values for this operation
     *
     * @throws \PAYJPV2\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \PAYJPV2\Model\PaymentMethodConfigurationListResponse|\PAYJPV2\Model\ErrorResponse|\PAYJPV2\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getAllPaymentMethodConfigurationsWithHttpInfo($limit = 10, $starting_after = null, $ending_before = null, string $contentType = self::contentTypes['getAllPaymentMethodConfigurations'][0])
    {
        $request = $this->getAllPaymentMethodConfigurationsRequest($limit, $starting_after, $ending_before, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\PAYJPV2\Model\PaymentMethodConfigurationListResponse',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\PAYJPV2\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\PAYJPV2\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\PAYJPV2\Model\PaymentMethodConfigurationListResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\PAYJPV2\Model\PaymentMethodConfigurationListResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\PAYJPV2\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\PAYJPV2\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getAllPaymentMethodConfigurationsAsync
     *
     * Get All Payment Method Configurations
     *
     * @param  int|null $limit 取得するデータの最大件数 (optional, default to 10)
     * @param  string|null $starting_after このIDより後のデータを取得 (optional)
     * @param  string|null $ending_before このIDより前のデータを取得 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAllPaymentMethodConfigurations'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAllPaymentMethodConfigurationsAsync($limit = 10, $starting_after = null, $ending_before = null, string $contentType = self::contentTypes['getAllPaymentMethodConfigurations'][0])
    {
        return $this->getAllPaymentMethodConfigurationsAsyncWithHttpInfo($limit, $starting_after, $ending_before, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getAllPaymentMethodConfigurationsAsyncWithHttpInfo
     *
     * Get All Payment Method Configurations
     *
     * @param  int|null $limit 取得するデータの最大件数 (optional, default to 10)
     * @param  string|null $starting_after このIDより後のデータを取得 (optional)
     * @param  string|null $ending_before このIDより前のデータを取得 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAllPaymentMethodConfigurations'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAllPaymentMethodConfigurationsAsyncWithHttpInfo($limit = 10, $starting_after = null, $ending_before = null, string $contentType = self::contentTypes['getAllPaymentMethodConfigurations'][0])
    {
        $returnType = '\PAYJPV2\Model\PaymentMethodConfigurationListResponse';
        $request = $this->getAllPaymentMethodConfigurationsRequest($limit, $starting_after, $ending_before, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getAllPaymentMethodConfigurations'
     *
     * @param  int|null $limit 取得するデータの最大件数 (optional, default to 10)
     * @param  string|null $starting_after このIDより後のデータを取得 (optional)
     * @param  string|null $ending_before このIDより前のデータを取得 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAllPaymentMethodConfigurations'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getAllPaymentMethodConfigurationsRequest($limit = 10, $starting_after = null, $ending_before = null, string $contentType = self::contentTypes['getAllPaymentMethodConfigurations'][0])
    {

        if ($limit !== null && $limit > 100) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling PaymentMethodConfigurationsApi.getAllPaymentMethodConfigurations, must be smaller than or equal to 100.');
        }
        if ($limit !== null && $limit < 1) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling PaymentMethodConfigurationsApi.getAllPaymentMethodConfigurations, must be bigger than or equal to 1.');
        }
        



        $resourcePath = '/v2/payment_method_configurations';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $starting_after,
            'starting_after', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $ending_before,
            'ending_before', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'application/problem+json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getPaymentMethodConfiguration
     *
     * Get Payment Method Configuration
     *
     * @param  string $payment_method_configuration_id payment_method_configuration_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPaymentMethodConfiguration'] to see the possible values for this operation
     *
     * @throws \PAYJPV2\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \PAYJPV2\Model\PaymentMethodConfigurationDetailsResponse|\PAYJPV2\Model\ErrorResponse
     */
    public function getPaymentMethodConfiguration($payment_method_configuration_id, string $contentType = self::contentTypes['getPaymentMethodConfiguration'][0])
    {
        list($response) = $this->getPaymentMethodConfigurationWithHttpInfo($payment_method_configuration_id, $contentType);
        return $response;
    }

    /**
     * Operation getPaymentMethodConfigurationWithHttpInfo
     *
     * Get Payment Method Configuration
     *
     * @param  string $payment_method_configuration_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPaymentMethodConfiguration'] to see the possible values for this operation
     *
     * @throws \PAYJPV2\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \PAYJPV2\Model\PaymentMethodConfigurationDetailsResponse|\PAYJPV2\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getPaymentMethodConfigurationWithHttpInfo($payment_method_configuration_id, string $contentType = self::contentTypes['getPaymentMethodConfiguration'][0])
    {
        $request = $this->getPaymentMethodConfigurationRequest($payment_method_configuration_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\PAYJPV2\Model\PaymentMethodConfigurationDetailsResponse',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\PAYJPV2\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\PAYJPV2\Model\PaymentMethodConfigurationDetailsResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\PAYJPV2\Model\PaymentMethodConfigurationDetailsResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\PAYJPV2\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getPaymentMethodConfigurationAsync
     *
     * Get Payment Method Configuration
     *
     * @param  string $payment_method_configuration_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPaymentMethodConfiguration'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getPaymentMethodConfigurationAsync($payment_method_configuration_id, string $contentType = self::contentTypes['getPaymentMethodConfiguration'][0])
    {
        return $this->getPaymentMethodConfigurationAsyncWithHttpInfo($payment_method_configuration_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getPaymentMethodConfigurationAsyncWithHttpInfo
     *
     * Get Payment Method Configuration
     *
     * @param  string $payment_method_configuration_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPaymentMethodConfiguration'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getPaymentMethodConfigurationAsyncWithHttpInfo($payment_method_configuration_id, string $contentType = self::contentTypes['getPaymentMethodConfiguration'][0])
    {
        $returnType = '\PAYJPV2\Model\PaymentMethodConfigurationDetailsResponse';
        $request = $this->getPaymentMethodConfigurationRequest($payment_method_configuration_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getPaymentMethodConfiguration'
     *
     * @param  string $payment_method_configuration_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPaymentMethodConfiguration'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getPaymentMethodConfigurationRequest($payment_method_configuration_id, string $contentType = self::contentTypes['getPaymentMethodConfiguration'][0])
    {

        // verify the required parameter 'payment_method_configuration_id' is set
        if ($payment_method_configuration_id === null || (is_array($payment_method_configuration_id) && count($payment_method_configuration_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $payment_method_configuration_id when calling getPaymentMethodConfiguration'
            );
        }


        $resourcePath = '/v2/payment_method_configurations/{payment_method_configuration_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($payment_method_configuration_id !== null) {
            $resourcePath = str_replace(
                '{' . 'payment_method_configuration_id' . '}',
                ObjectSerializer::toPathValue($payment_method_configuration_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'application/problem+json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation updatePaymentMethodConfiguration
     *
     * Update Payment Method Configuration
     *
     * @param  string $payment_method_configuration_id payment_method_configuration_id (required)
     * @param  \PAYJPV2\Model\PaymentMethodConfigurationUpdateRequest $payment_method_configuration_update_request payment_method_configuration_update_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updatePaymentMethodConfiguration'] to see the possible values for this operation
     *
     * @throws \PAYJPV2\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \PAYJPV2\Model\PaymentMethodConfigurationDetailsResponse|\PAYJPV2\Model\ErrorResponse
     */
    public function updatePaymentMethodConfiguration($payment_method_configuration_id, $payment_method_configuration_update_request, string $contentType = self::contentTypes['updatePaymentMethodConfiguration'][0])
    {
        list($response) = $this->updatePaymentMethodConfigurationWithHttpInfo($payment_method_configuration_id, $payment_method_configuration_update_request, $contentType);
        return $response;
    }

    /**
     * Operation updatePaymentMethodConfigurationWithHttpInfo
     *
     * Update Payment Method Configuration
     *
     * @param  string $payment_method_configuration_id (required)
     * @param  \PAYJPV2\Model\PaymentMethodConfigurationUpdateRequest $payment_method_configuration_update_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updatePaymentMethodConfiguration'] to see the possible values for this operation
     *
     * @throws \PAYJPV2\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \PAYJPV2\Model\PaymentMethodConfigurationDetailsResponse|\PAYJPV2\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function updatePaymentMethodConfigurationWithHttpInfo($payment_method_configuration_id, $payment_method_configuration_update_request, string $contentType = self::contentTypes['updatePaymentMethodConfiguration'][0])
    {
        $request = $this->updatePaymentMethodConfigurationRequest($payment_method_configuration_id, $payment_method_configuration_update_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\PAYJPV2\Model\PaymentMethodConfigurationDetailsResponse',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\PAYJPV2\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\PAYJPV2\Model\PaymentMethodConfigurationDetailsResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\PAYJPV2\Model\PaymentMethodConfigurationDetailsResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\PAYJPV2\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation updatePaymentMethodConfigurationAsync
     *
     * Update Payment Method Configuration
     *
     * @param  string $payment_method_configuration_id (required)
     * @param  \PAYJPV2\Model\PaymentMethodConfigurationUpdateRequest $payment_method_configuration_update_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updatePaymentMethodConfiguration'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updatePaymentMethodConfigurationAsync($payment_method_configuration_id, $payment_method_configuration_update_request, string $contentType = self::contentTypes['updatePaymentMethodConfiguration'][0])
    {
        return $this->updatePaymentMethodConfigurationAsyncWithHttpInfo($payment_method_configuration_id, $payment_method_configuration_update_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation updatePaymentMethodConfigurationAsyncWithHttpInfo
     *
     * Update Payment Method Configuration
     *
     * @param  string $payment_method_configuration_id (required)
     * @param  \PAYJPV2\Model\PaymentMethodConfigurationUpdateRequest $payment_method_configuration_update_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updatePaymentMethodConfiguration'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updatePaymentMethodConfigurationAsyncWithHttpInfo($payment_method_configuration_id, $payment_method_configuration_update_request, string $contentType = self::contentTypes['updatePaymentMethodConfiguration'][0])
    {
        $returnType = '\PAYJPV2\Model\PaymentMethodConfigurationDetailsResponse';
        $request = $this->updatePaymentMethodConfigurationRequest($payment_method_configuration_id, $payment_method_configuration_update_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'updatePaymentMethodConfiguration'
     *
     * @param  string $payment_method_configuration_id (required)
     * @param  \PAYJPV2\Model\PaymentMethodConfigurationUpdateRequest $payment_method_configuration_update_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updatePaymentMethodConfiguration'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function updatePaymentMethodConfigurationRequest($payment_method_configuration_id, $payment_method_configuration_update_request, string $contentType = self::contentTypes['updatePaymentMethodConfiguration'][0])
    {

        // verify the required parameter 'payment_method_configuration_id' is set
        if ($payment_method_configuration_id === null || (is_array($payment_method_configuration_id) && count($payment_method_configuration_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $payment_method_configuration_id when calling updatePaymentMethodConfiguration'
            );
        }

        // verify the required parameter 'payment_method_configuration_update_request' is set
        if ($payment_method_configuration_update_request === null || (is_array($payment_method_configuration_update_request) && count($payment_method_configuration_update_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $payment_method_configuration_update_request when calling updatePaymentMethodConfiguration'
            );
        }


        $resourcePath = '/v2/payment_method_configurations/{payment_method_configuration_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($payment_method_configuration_id !== null) {
            $resourcePath = str_replace(
                '{' . 'payment_method_configuration_id' . '}',
                ObjectSerializer::toPathValue($payment_method_configuration_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'application/problem+json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($payment_method_configuration_update_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($payment_method_configuration_update_request));
            } else {
                $httpBody = $payment_method_configuration_update_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
