<?php

/**
 * SetupFlowsApi
 * PHP version 8.1
 *
 * @category Class
 * @package  PAYJPV2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PAY.JP API v2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PAYJPV2\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use PAYJPV2\ApiException;
use PAYJPV2\Configuration;
use PAYJPV2\HeaderSelector;
use PAYJPV2\ObjectSerializer;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;

/**
 * SetupFlowsApi Class Doc Comment
 *
 * @category Class
 * @package  PAYJPV2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SetupFlowsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] * */
    public const contentTypes = [
        'cancelSetupFlow' => [
            'application/json',
        ],
        'createSetupFlow' => [
            'application/json',
        ],
        'getAllSetupFlows' => [
            'application/json',
        ],
        'getSetupFlow' => [
            'application/json',
        ],
        'updateSetupFlow' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation cancelSetupFlow
     *
     * Cancel Setup Flow
     *
     * @param  string $setupFlowId setupFlowId (required)
     * @param  \PAYJPV2\Model\SetupFlowCancelRequest|null $setupFlowCancelRequest setupFlowCancelRequest (optional)
     * @param  string|null $idempotencyKey Idempotency key for the request
     *
     * @throws \PAYJPV2\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \PAYJPV2\Model\SetupFlowResponse|\PAYJPV2\Model\ErrorResponse|\PAYJPV2\Model\ErrorResponse|\PAYJPV2\Model\ErrorResponse
     */
    public function cancelSetupFlow($setupFlowId, $setupFlowCancelRequest = null, ?string $idempotencyKey = null)
    {
        list($response) = $this->cancelSetupFlowWithHttpInfo($setupFlowId, $setupFlowCancelRequest, $idempotencyKey);

        return $response;
    }

    /**
     * Operation cancelSetupFlowWithHttpInfo
     *
     * Cancel Setup Flow
     *
     * @param  string $setupFlowId (required)
     * @param  \PAYJPV2\Model\SetupFlowCancelRequest|null $setupFlowCancelRequest (optional)
     * @param  string|null $idempotencyKey Idempotency key for the request
     *
     * @throws \PAYJPV2\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \PAYJPV2\Model\SetupFlowResponse|\PAYJPV2\Model\ErrorResponse|\PAYJPV2\Model\ErrorResponse|\PAYJPV2\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function cancelSetupFlowWithHttpInfo($setupFlowId, $setupFlowCancelRequest = null, ?string $idempotencyKey = null)
    {
        $request = $this->cancelSetupFlowRequest($setupFlowId, $setupFlowCancelRequest, $idempotencyKey);

        try {
            $options = $this->createHttpClientOption();

            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch ($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\PAYJPV2\Model\SetupFlowResponse',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\PAYJPV2\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\PAYJPV2\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\PAYJPV2\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }



            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\PAYJPV2\Model\SetupFlowResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\PAYJPV2\Model\SetupFlowResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);

                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\PAYJPV2\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);

                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\PAYJPV2\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);

                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\PAYJPV2\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);

                    throw $e;
            }


            throw $e;
        }
    }

    /**
     * Operation cancelSetupFlowAsync
     *
     * Cancel Setup Flow
     *
     * @param  string $setupFlowId (required)
     * @param  \PAYJPV2\Model\SetupFlowCancelRequest|null $setupFlowCancelRequest (optional)
     * @param  string|null $idempotencyKey Idempotency key for the request
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function cancelSetupFlowAsync($setupFlowId, $setupFlowCancelRequest = null, ?string $idempotencyKey = null)
    {
        return $this->cancelSetupFlowAsyncWithHttpInfo($setupFlowId, $setupFlowCancelRequest, $idempotencyKey)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation cancelSetupFlowAsyncWithHttpInfo
     *
     * Cancel Setup Flow
     *
     * @param  string $setupFlowId (required)
     * @param  \PAYJPV2\Model\SetupFlowCancelRequest|null $setupFlowCancelRequest (optional)
     * @param  string|null $idempotencyKey Idempotency key for the request
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function cancelSetupFlowAsyncWithHttpInfo($setupFlowId, $setupFlowCancelRequest = null, ?string $idempotencyKey = null)
    {
        $returnType = '\PAYJPV2\Model\SetupFlowResponse';
        $request = $this->cancelSetupFlowRequest($setupFlowId, $setupFlowCancelRequest, $idempotencyKey);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();

                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'cancelSetupFlow'
     *
     * @param  string $setupFlowId (required)
     * @param  \PAYJPV2\Model\SetupFlowCancelRequest|null $setupFlowCancelRequest (optional)
     * @param  string|null $idempotencyKey Idempotency key for the request
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function cancelSetupFlowRequest($setupFlowId, $setupFlowCancelRequest = null, ?string $idempotencyKey = null)
    {

        // verify the required parameter 'setupFlowId' is set
        if ($setupFlowId === null || (is_array($setupFlowId) && count($setupFlowId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $setupFlowId when calling cancelSetupFlow'
            );
        }



        $resourcePath = '/v2/setup_flows/{setup_flow_id}/cancel';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // idempotency key
        if ($idempotencyKey !== null) {
            $headerParams['Idempotency-Key'] = $idempotencyKey;
        }



        // path params
        if ($setupFlowId !== null) {
            $resourcePath = str_replace(
                '{' . 'setup_flow_id' . '}',
                ObjectSerializer::toPathValue($setupFlowId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'application/problem+json', ],
            'application/json',
            $multipart
        );

        // for model (json/xml)
        if (isset($setupFlowCancelRequest)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($setupFlowCancelRequest));
            } else {
                $httpBody = $setupFlowCancelRequest;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem,
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (! empty($this->config->getUsername()) || ! (empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires Bearer authentication (access token)
        if (! empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        $defaultHeaders['X-Payjp-Client-User-Agent'] = Configuration::buildClientUserAgent();

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);

        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation createSetupFlow
     *
     * Create Setup Flow
     *
     * @param  \PAYJPV2\Model\SetupFlowCreateRequest|null $setupFlowCreateRequest setupFlowCreateRequest (optional)
     * @param  string|null $idempotencyKey Idempotency key for the request
     *
     * @throws \PAYJPV2\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \PAYJPV2\Model\SetupFlowResponse|\PAYJPV2\Model\ErrorResponse|\PAYJPV2\Model\ErrorResponse|\PAYJPV2\Model\ErrorResponse
     */
    public function createSetupFlow($setupFlowCreateRequest = null, ?string $idempotencyKey = null)
    {
        list($response) = $this->createSetupFlowWithHttpInfo($setupFlowCreateRequest, $idempotencyKey);

        return $response;
    }

    /**
     * Operation createSetupFlowWithHttpInfo
     *
     * Create Setup Flow
     *
     * @param  \PAYJPV2\Model\SetupFlowCreateRequest|null $setupFlowCreateRequest (optional)
     * @param  string|null $idempotencyKey Idempotency key for the request
     *
     * @throws \PAYJPV2\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \PAYJPV2\Model\SetupFlowResponse|\PAYJPV2\Model\ErrorResponse|\PAYJPV2\Model\ErrorResponse|\PAYJPV2\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function createSetupFlowWithHttpInfo($setupFlowCreateRequest = null, ?string $idempotencyKey = null)
    {
        $request = $this->createSetupFlowRequest($setupFlowCreateRequest, $idempotencyKey);

        try {
            $options = $this->createHttpClientOption();

            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch ($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\PAYJPV2\Model\SetupFlowResponse',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\PAYJPV2\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\PAYJPV2\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\PAYJPV2\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }



            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\PAYJPV2\Model\SetupFlowResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\PAYJPV2\Model\SetupFlowResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);

                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\PAYJPV2\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);

                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\PAYJPV2\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);

                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\PAYJPV2\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);

                    throw $e;
            }


            throw $e;
        }
    }

    /**
     * Operation createSetupFlowAsync
     *
     * Create Setup Flow
     *
     * @param  \PAYJPV2\Model\SetupFlowCreateRequest|null $setupFlowCreateRequest (optional)
     * @param  string|null $idempotencyKey Idempotency key for the request
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createSetupFlowAsync($setupFlowCreateRequest = null, ?string $idempotencyKey = null)
    {
        return $this->createSetupFlowAsyncWithHttpInfo($setupFlowCreateRequest, $idempotencyKey)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createSetupFlowAsyncWithHttpInfo
     *
     * Create Setup Flow
     *
     * @param  \PAYJPV2\Model\SetupFlowCreateRequest|null $setupFlowCreateRequest (optional)
     * @param  string|null $idempotencyKey Idempotency key for the request
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createSetupFlowAsyncWithHttpInfo($setupFlowCreateRequest = null, ?string $idempotencyKey = null)
    {
        $returnType = '\PAYJPV2\Model\SetupFlowResponse';
        $request = $this->createSetupFlowRequest($setupFlowCreateRequest, $idempotencyKey);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();

                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createSetupFlow'
     *
     * @param  \PAYJPV2\Model\SetupFlowCreateRequest|null $setupFlowCreateRequest (optional)
     * @param  string|null $idempotencyKey Idempotency key for the request
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createSetupFlowRequest($setupFlowCreateRequest = null, ?string $idempotencyKey = null)
    {



        $resourcePath = '/v2/setup_flows';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // idempotency key
        if ($idempotencyKey !== null) {
            $headerParams['Idempotency-Key'] = $idempotencyKey;
        }





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'application/problem+json', ],
            'application/json',
            $multipart
        );

        // for model (json/xml)
        if (isset($setupFlowCreateRequest)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($setupFlowCreateRequest));
            } else {
                $httpBody = $setupFlowCreateRequest;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem,
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (! empty($this->config->getUsername()) || ! (empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires Bearer authentication (access token)
        if (! empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        $defaultHeaders['X-Payjp-Client-User-Agent'] = Configuration::buildClientUserAgent();

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);

        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getAllSetupFlows
     *
     * Get All Setup Flows
     *
     * @param  int|null $limit 取得するデータの最大件数 (optional, default to 10)
     * @param  string|null $startingAfter このIDより後のデータを取得 (optional)
     * @param  string|null $endingBefore このIDより前のデータを取得 (optional)
     * @param  string|null $idempotencyKey Idempotency key for the request
     *
     * @throws \PAYJPV2\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \PAYJPV2\Model\SetupFlowListResponse|\PAYJPV2\Model\ErrorResponse|\PAYJPV2\Model\ErrorResponse
     */
    public function getAllSetupFlows($limit = 10, $startingAfter = null, $endingBefore = null, ?string $idempotencyKey = null)
    {
        list($response) = $this->getAllSetupFlowsWithHttpInfo($limit, $startingAfter, $endingBefore, $idempotencyKey);

        return $response;
    }

    /**
     * Operation getAllSetupFlowsWithHttpInfo
     *
     * Get All Setup Flows
     *
     * @param  int|null $limit 取得するデータの最大件数 (optional, default to 10)
     * @param  string|null $startingAfter このIDより後のデータを取得 (optional)
     * @param  string|null $endingBefore このIDより前のデータを取得 (optional)
     * @param  string|null $idempotencyKey Idempotency key for the request
     *
     * @throws \PAYJPV2\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \PAYJPV2\Model\SetupFlowListResponse|\PAYJPV2\Model\ErrorResponse|\PAYJPV2\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getAllSetupFlowsWithHttpInfo($limit = 10, $startingAfter = null, $endingBefore = null, ?string $idempotencyKey = null)
    {
        $request = $this->getAllSetupFlowsRequest($limit, $startingAfter, $endingBefore, $idempotencyKey);

        try {
            $options = $this->createHttpClientOption();

            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch ($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\PAYJPV2\Model\SetupFlowListResponse',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\PAYJPV2\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\PAYJPV2\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }



            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\PAYJPV2\Model\SetupFlowListResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\PAYJPV2\Model\SetupFlowListResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);

                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\PAYJPV2\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);

                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\PAYJPV2\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);

                    throw $e;
            }


            throw $e;
        }
    }

    /**
     * Operation getAllSetupFlowsAsync
     *
     * Get All Setup Flows
     *
     * @param  int|null $limit 取得するデータの最大件数 (optional, default to 10)
     * @param  string|null $startingAfter このIDより後のデータを取得 (optional)
     * @param  string|null $endingBefore このIDより前のデータを取得 (optional)
     * @param  string|null $idempotencyKey Idempotency key for the request
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAllSetupFlowsAsync($limit = 10, $startingAfter = null, $endingBefore = null, ?string $idempotencyKey = null)
    {
        return $this->getAllSetupFlowsAsyncWithHttpInfo($limit, $startingAfter, $endingBefore, $idempotencyKey)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getAllSetupFlowsAsyncWithHttpInfo
     *
     * Get All Setup Flows
     *
     * @param  int|null $limit 取得するデータの最大件数 (optional, default to 10)
     * @param  string|null $startingAfter このIDより後のデータを取得 (optional)
     * @param  string|null $endingBefore このIDより前のデータを取得 (optional)
     * @param  string|null $idempotencyKey Idempotency key for the request
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAllSetupFlowsAsyncWithHttpInfo($limit = 10, $startingAfter = null, $endingBefore = null, ?string $idempotencyKey = null)
    {
        $returnType = '\PAYJPV2\Model\SetupFlowListResponse';
        $request = $this->getAllSetupFlowsRequest($limit, $startingAfter, $endingBefore, $idempotencyKey);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();

                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getAllSetupFlows'
     *
     * @param  int|null $limit 取得するデータの最大件数 (optional, default to 10)
     * @param  string|null $startingAfter このIDより後のデータを取得 (optional)
     * @param  string|null $endingBefore このIDより前のデータを取得 (optional)
     * @param  string|null $idempotencyKey Idempotency key for the request
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getAllSetupFlowsRequest($limit = 10, $startingAfter = null, $endingBefore = null, ?string $idempotencyKey = null)
    {

        if ($limit !== null && $limit > 100) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling SetupFlowsApi.getAllSetupFlows, must be smaller than or equal to 100.');
        }
        if ($limit !== null && $limit < 1) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling SetupFlowsApi.getAllSetupFlows, must be bigger than or equal to 1.');
        }




        $resourcePath = '/v2/setup_flows';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // idempotency key
        if ($idempotencyKey !== null) {
            $headerParams['Idempotency-Key'] = $idempotencyKey;
        }

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $startingAfter,
            'starting_after', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $endingBefore,
            'ending_before', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'application/problem+json', ],
            'application/json',
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem,
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (! empty($this->config->getUsername()) || ! (empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires Bearer authentication (access token)
        if (! empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        $defaultHeaders['X-Payjp-Client-User-Agent'] = Configuration::buildClientUserAgent();

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);

        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getSetupFlow
     *
     * Get Setup Flow
     *
     * @param  string $setupFlowId setupFlowId (required)
     * @param  string|null $idempotencyKey Idempotency key for the request
     *
     * @throws \PAYJPV2\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \PAYJPV2\Model\SetupFlowResponse|\PAYJPV2\Model\ErrorResponse|\PAYJPV2\Model\ErrorResponse
     */
    public function getSetupFlow($setupFlowId, ?string $idempotencyKey = null)
    {
        list($response) = $this->getSetupFlowWithHttpInfo($setupFlowId, $idempotencyKey);

        return $response;
    }

    /**
     * Operation getSetupFlowWithHttpInfo
     *
     * Get Setup Flow
     *
     * @param  string $setupFlowId (required)
     * @param  string|null $idempotencyKey Idempotency key for the request
     *
     * @throws \PAYJPV2\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \PAYJPV2\Model\SetupFlowResponse|\PAYJPV2\Model\ErrorResponse|\PAYJPV2\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getSetupFlowWithHttpInfo($setupFlowId, ?string $idempotencyKey = null)
    {
        $request = $this->getSetupFlowRequest($setupFlowId, $idempotencyKey);

        try {
            $options = $this->createHttpClientOption();

            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch ($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\PAYJPV2\Model\SetupFlowResponse',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\PAYJPV2\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\PAYJPV2\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }



            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\PAYJPV2\Model\SetupFlowResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\PAYJPV2\Model\SetupFlowResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);

                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\PAYJPV2\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);

                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\PAYJPV2\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);

                    throw $e;
            }


            throw $e;
        }
    }

    /**
     * Operation getSetupFlowAsync
     *
     * Get Setup Flow
     *
     * @param  string $setupFlowId (required)
     * @param  string|null $idempotencyKey Idempotency key for the request
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSetupFlowAsync($setupFlowId, ?string $idempotencyKey = null)
    {
        return $this->getSetupFlowAsyncWithHttpInfo($setupFlowId, $idempotencyKey)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getSetupFlowAsyncWithHttpInfo
     *
     * Get Setup Flow
     *
     * @param  string $setupFlowId (required)
     * @param  string|null $idempotencyKey Idempotency key for the request
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSetupFlowAsyncWithHttpInfo($setupFlowId, ?string $idempotencyKey = null)
    {
        $returnType = '\PAYJPV2\Model\SetupFlowResponse';
        $request = $this->getSetupFlowRequest($setupFlowId, $idempotencyKey);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();

                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getSetupFlow'
     *
     * @param  string $setupFlowId (required)
     * @param  string|null $idempotencyKey Idempotency key for the request
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getSetupFlowRequest($setupFlowId, ?string $idempotencyKey = null)
    {

        // verify the required parameter 'setupFlowId' is set
        if ($setupFlowId === null || (is_array($setupFlowId) && count($setupFlowId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $setupFlowId when calling getSetupFlow'
            );
        }


        $resourcePath = '/v2/setup_flows/{setup_flow_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // idempotency key
        if ($idempotencyKey !== null) {
            $headerParams['Idempotency-Key'] = $idempotencyKey;
        }



        // path params
        if ($setupFlowId !== null) {
            $resourcePath = str_replace(
                '{' . 'setup_flow_id' . '}',
                ObjectSerializer::toPathValue($setupFlowId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'application/problem+json', ],
            'application/json',
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem,
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (! empty($this->config->getUsername()) || ! (empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires Bearer authentication (access token)
        if (! empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        $defaultHeaders['X-Payjp-Client-User-Agent'] = Configuration::buildClientUserAgent();

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);

        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation updateSetupFlow
     *
     * Update Setup Flow
     *
     * @param  string $setupFlowId setupFlowId (required)
     * @param  \PAYJPV2\Model\SetupFlowUpdateRequest $setupFlowUpdateRequest setupFlowUpdateRequest (required)
     * @param  string|null $idempotencyKey Idempotency key for the request
     *
     * @throws \PAYJPV2\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \PAYJPV2\Model\SetupFlowResponse|\PAYJPV2\Model\ErrorResponse|\PAYJPV2\Model\ErrorResponse|\PAYJPV2\Model\ErrorResponse
     */
    public function updateSetupFlow($setupFlowId, $setupFlowUpdateRequest, ?string $idempotencyKey = null)
    {
        list($response) = $this->updateSetupFlowWithHttpInfo($setupFlowId, $setupFlowUpdateRequest, $idempotencyKey);

        return $response;
    }

    /**
     * Operation updateSetupFlowWithHttpInfo
     *
     * Update Setup Flow
     *
     * @param  string $setupFlowId (required)
     * @param  \PAYJPV2\Model\SetupFlowUpdateRequest $setupFlowUpdateRequest (required)
     * @param  string|null $idempotencyKey Idempotency key for the request
     *
     * @throws \PAYJPV2\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \PAYJPV2\Model\SetupFlowResponse|\PAYJPV2\Model\ErrorResponse|\PAYJPV2\Model\ErrorResponse|\PAYJPV2\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateSetupFlowWithHttpInfo($setupFlowId, $setupFlowUpdateRequest, ?string $idempotencyKey = null)
    {
        $request = $this->updateSetupFlowRequest($setupFlowId, $setupFlowUpdateRequest, $idempotencyKey);

        try {
            $options = $this->createHttpClientOption();

            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch ($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\PAYJPV2\Model\SetupFlowResponse',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\PAYJPV2\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\PAYJPV2\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\PAYJPV2\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }



            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\PAYJPV2\Model\SetupFlowResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\PAYJPV2\Model\SetupFlowResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);

                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\PAYJPV2\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);

                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\PAYJPV2\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);

                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\PAYJPV2\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);

                    throw $e;
            }


            throw $e;
        }
    }

    /**
     * Operation updateSetupFlowAsync
     *
     * Update Setup Flow
     *
     * @param  string $setupFlowId (required)
     * @param  \PAYJPV2\Model\SetupFlowUpdateRequest $setupFlowUpdateRequest (required)
     * @param  string|null $idempotencyKey Idempotency key for the request
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateSetupFlowAsync($setupFlowId, $setupFlowUpdateRequest, ?string $idempotencyKey = null)
    {
        return $this->updateSetupFlowAsyncWithHttpInfo($setupFlowId, $setupFlowUpdateRequest, $idempotencyKey)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation updateSetupFlowAsyncWithHttpInfo
     *
     * Update Setup Flow
     *
     * @param  string $setupFlowId (required)
     * @param  \PAYJPV2\Model\SetupFlowUpdateRequest $setupFlowUpdateRequest (required)
     * @param  string|null $idempotencyKey Idempotency key for the request
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateSetupFlowAsyncWithHttpInfo($setupFlowId, $setupFlowUpdateRequest, ?string $idempotencyKey = null)
    {
        $returnType = '\PAYJPV2\Model\SetupFlowResponse';
        $request = $this->updateSetupFlowRequest($setupFlowId, $setupFlowUpdateRequest, $idempotencyKey);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();

                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'updateSetupFlow'
     *
     * @param  string $setupFlowId (required)
     * @param  \PAYJPV2\Model\SetupFlowUpdateRequest $setupFlowUpdateRequest (required)
     * @param  string|null $idempotencyKey Idempotency key for the request
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function updateSetupFlowRequest($setupFlowId, $setupFlowUpdateRequest, ?string $idempotencyKey = null)
    {

        // verify the required parameter 'setupFlowId' is set
        if ($setupFlowId === null || (is_array($setupFlowId) && count($setupFlowId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $setupFlowId when calling updateSetupFlow'
            );
        }

        // verify the required parameter 'setupFlowUpdateRequest' is set
        if ($setupFlowUpdateRequest === null || (is_array($setupFlowUpdateRequest) && count($setupFlowUpdateRequest) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $setupFlowUpdateRequest when calling updateSetupFlow'
            );
        }


        $resourcePath = '/v2/setup_flows/{setup_flow_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // idempotency key
        if ($idempotencyKey !== null) {
            $headerParams['Idempotency-Key'] = $idempotencyKey;
        }



        // path params
        if ($setupFlowId !== null) {
            $resourcePath = str_replace(
                '{' . 'setup_flow_id' . '}',
                ObjectSerializer::toPathValue($setupFlowId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'application/problem+json', ],
            'application/json',
            $multipart
        );

        // for model (json/xml)
        if (isset($setupFlowUpdateRequest)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($setupFlowUpdateRequest));
            } else {
                $httpBody = $setupFlowUpdateRequest;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem,
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (! empty($this->config->getUsername()) || ! (empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires Bearer authentication (access token)
        if (! empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        $defaultHeaders['X-Payjp-Client-User-Agent'] = Configuration::buildClientUserAgent();

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);

        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (! $options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders(),
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
