<?php

/**
 * StatementsApi
 * PHP version 8.1
 *
 * @category Class
 * @package  PAYJPV2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PAY.JP API v2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PAYJPV2\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use PAYJPV2\ApiException;
use PAYJPV2\Configuration;
use PAYJPV2\HeaderSelector;
use PAYJPV2\ObjectSerializer;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;

/**
 * StatementsApi Class Doc Comment
 *
 * @category Class
 * @package  PAYJPV2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class StatementsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] * */
    public const contentTypes = [
        'createStatementUrl' => [
            'application/json',
        ],
        'getAllStatements' => [
            'application/json',
        ],
        'getStatement' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createStatementUrl
     *
     * Create Statement Url
     *
     * @param  string $statementId statementId (required)
     * @param  string|null $idempotencyKey Idempotency key for the request
     *
     * @throws \PAYJPV2\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \PAYJPV2\Model\StatementURLResponse|\PAYJPV2\Model\ErrorResponse|\PAYJPV2\Model\ErrorResponse
     */
    public function createStatementUrl($statementId, ?string $idempotencyKey = null)
    {
        list($response) = $this->createStatementUrlWithHttpInfo($statementId, $idempotencyKey);

        return $response;
    }

    /**
     * Operation createStatementUrlWithHttpInfo
     *
     * Create Statement Url
     *
     * @param  string $statementId (required)
     * @param  string|null $idempotencyKey Idempotency key for the request
     *
     * @throws \PAYJPV2\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \PAYJPV2\Model\StatementURLResponse|\PAYJPV2\Model\ErrorResponse|\PAYJPV2\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function createStatementUrlWithHttpInfo($statementId, ?string $idempotencyKey = null)
    {
        $request = $this->createStatementUrlRequest($statementId, $idempotencyKey);

        try {
            $options = $this->createHttpClientOption();

            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch ($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\PAYJPV2\Model\StatementURLResponse',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\PAYJPV2\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\PAYJPV2\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }



            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\PAYJPV2\Model\StatementURLResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\PAYJPV2\Model\StatementURLResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);

                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\PAYJPV2\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);

                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\PAYJPV2\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);

                    throw $e;
            }


            throw $e;
        }
    }

    /**
     * Operation createStatementUrlAsync
     *
     * Create Statement Url
     *
     * @param  string $statementId (required)
     * @param  string|null $idempotencyKey Idempotency key for the request
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createStatementUrlAsync($statementId, ?string $idempotencyKey = null)
    {
        return $this->createStatementUrlAsyncWithHttpInfo($statementId, $idempotencyKey)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createStatementUrlAsyncWithHttpInfo
     *
     * Create Statement Url
     *
     * @param  string $statementId (required)
     * @param  string|null $idempotencyKey Idempotency key for the request
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createStatementUrlAsyncWithHttpInfo($statementId, ?string $idempotencyKey = null)
    {
        $returnType = '\PAYJPV2\Model\StatementURLResponse';
        $request = $this->createStatementUrlRequest($statementId, $idempotencyKey);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();

                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createStatementUrl'
     *
     * @param  string $statementId (required)
     * @param  string|null $idempotencyKey Idempotency key for the request
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createStatementUrlRequest($statementId, ?string $idempotencyKey = null)
    {

        // verify the required parameter 'statementId' is set
        if ($statementId === null || (is_array($statementId) && count($statementId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $statementId when calling createStatementUrl'
            );
        }


        $resourcePath = '/v2/statements/{statement_id}/statement_urls';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // idempotency key
        if ($idempotencyKey !== null) {
            $headerParams['Idempotency-Key'] = $idempotencyKey;
        }



        // path params
        if ($statementId !== null) {
            $resourcePath = str_replace(
                '{' . 'statement_id' . '}',
                ObjectSerializer::toPathValue($statementId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'application/problem+json', ],
            'application/json',
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem,
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (! empty($this->config->getUsername()) || ! (empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires Bearer authentication (access token)
        if (! empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        $defaultHeaders['X-Payjp-Client-User-Agent'] = Configuration::buildClientUserAgent();

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);

        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getAllStatements
     *
     * Get All Statements
     *
     * @param  \DateTime|null $since 指定した日付以降のデータを取得 (optional)
     * @param  \DateTime|null $until 指定した日付以前のデータを取得 (optional)
     * @param  int|null $limit 取得するデータの最大件数 (optional, default to 10)
     * @param  string|null $startingAfter このIDより後のデータを取得 (optional)
     * @param  string|null $endingBefore このIDより前のデータを取得 (optional)
     * @param  \PAYJPV2\Model\StatementType|null $type 明細タイプでフィルタ (optional)
     * @param  string|null $termId 期間IDでフィルタ (optional)
     * @param  string|null $idempotencyKey Idempotency key for the request
     *
     * @throws \PAYJPV2\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \PAYJPV2\Model\StatementListResponse|\PAYJPV2\Model\ErrorResponse|\PAYJPV2\Model\ErrorResponse
     */
    public function getAllStatements($since = null, $until = null, $limit = 10, $startingAfter = null, $endingBefore = null, $type = null, $termId = null, ?string $idempotencyKey = null)
    {
        list($response) = $this->getAllStatementsWithHttpInfo($since, $until, $limit, $startingAfter, $endingBefore, $type, $termId, $idempotencyKey);

        return $response;
    }

    /**
     * Operation getAllStatementsWithHttpInfo
     *
     * Get All Statements
     *
     * @param  \DateTime|null $since 指定した日付以降のデータを取得 (optional)
     * @param  \DateTime|null $until 指定した日付以前のデータを取得 (optional)
     * @param  int|null $limit 取得するデータの最大件数 (optional, default to 10)
     * @param  string|null $startingAfter このIDより後のデータを取得 (optional)
     * @param  string|null $endingBefore このIDより前のデータを取得 (optional)
     * @param  \PAYJPV2\Model\StatementType|null $type 明細タイプでフィルタ (optional)
     * @param  string|null $termId 期間IDでフィルタ (optional)
     * @param  string|null $idempotencyKey Idempotency key for the request
     *
     * @throws \PAYJPV2\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \PAYJPV2\Model\StatementListResponse|\PAYJPV2\Model\ErrorResponse|\PAYJPV2\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getAllStatementsWithHttpInfo($since = null, $until = null, $limit = 10, $startingAfter = null, $endingBefore = null, $type = null, $termId = null, ?string $idempotencyKey = null)
    {
        $request = $this->getAllStatementsRequest($since, $until, $limit, $startingAfter, $endingBefore, $type, $termId, $idempotencyKey);

        try {
            $options = $this->createHttpClientOption();

            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch ($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\PAYJPV2\Model\StatementListResponse',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\PAYJPV2\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\PAYJPV2\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }



            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\PAYJPV2\Model\StatementListResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\PAYJPV2\Model\StatementListResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);

                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\PAYJPV2\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);

                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\PAYJPV2\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);

                    throw $e;
            }


            throw $e;
        }
    }

    /**
     * Operation getAllStatementsAsync
     *
     * Get All Statements
     *
     * @param  \DateTime|null $since 指定した日付以降のデータを取得 (optional)
     * @param  \DateTime|null $until 指定した日付以前のデータを取得 (optional)
     * @param  int|null $limit 取得するデータの最大件数 (optional, default to 10)
     * @param  string|null $startingAfter このIDより後のデータを取得 (optional)
     * @param  string|null $endingBefore このIDより前のデータを取得 (optional)
     * @param  \PAYJPV2\Model\StatementType|null $type 明細タイプでフィルタ (optional)
     * @param  string|null $termId 期間IDでフィルタ (optional)
     * @param  string|null $idempotencyKey Idempotency key for the request
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAllStatementsAsync($since = null, $until = null, $limit = 10, $startingAfter = null, $endingBefore = null, $type = null, $termId = null, ?string $idempotencyKey = null)
    {
        return $this->getAllStatementsAsyncWithHttpInfo($since, $until, $limit, $startingAfter, $endingBefore, $type, $termId, $idempotencyKey)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getAllStatementsAsyncWithHttpInfo
     *
     * Get All Statements
     *
     * @param  \DateTime|null $since 指定した日付以降のデータを取得 (optional)
     * @param  \DateTime|null $until 指定した日付以前のデータを取得 (optional)
     * @param  int|null $limit 取得するデータの最大件数 (optional, default to 10)
     * @param  string|null $startingAfter このIDより後のデータを取得 (optional)
     * @param  string|null $endingBefore このIDより前のデータを取得 (optional)
     * @param  \PAYJPV2\Model\StatementType|null $type 明細タイプでフィルタ (optional)
     * @param  string|null $termId 期間IDでフィルタ (optional)
     * @param  string|null $idempotencyKey Idempotency key for the request
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAllStatementsAsyncWithHttpInfo($since = null, $until = null, $limit = 10, $startingAfter = null, $endingBefore = null, $type = null, $termId = null, ?string $idempotencyKey = null)
    {
        $returnType = '\PAYJPV2\Model\StatementListResponse';
        $request = $this->getAllStatementsRequest($since, $until, $limit, $startingAfter, $endingBefore, $type, $termId, $idempotencyKey);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();

                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getAllStatements'
     *
     * @param  \DateTime|null $since 指定した日付以降のデータを取得 (optional)
     * @param  \DateTime|null $until 指定した日付以前のデータを取得 (optional)
     * @param  int|null $limit 取得するデータの最大件数 (optional, default to 10)
     * @param  string|null $startingAfter このIDより後のデータを取得 (optional)
     * @param  string|null $endingBefore このIDより前のデータを取得 (optional)
     * @param  \PAYJPV2\Model\StatementType|null $type 明細タイプでフィルタ (optional)
     * @param  string|null $termId 期間IDでフィルタ (optional)
     * @param  string|null $idempotencyKey Idempotency key for the request
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getAllStatementsRequest($since = null, $until = null, $limit = 10, $startingAfter = null, $endingBefore = null, $type = null, $termId = null, ?string $idempotencyKey = null)
    {



        if ($limit !== null && $limit > 100) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling StatementsApi.getAllStatements, must be smaller than or equal to 100.');
        }
        if ($limit !== null && $limit < 1) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling StatementsApi.getAllStatements, must be bigger than or equal to 1.');
        }






        $resourcePath = '/v2/statements';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // idempotency key
        if ($idempotencyKey !== null) {
            $headerParams['Idempotency-Key'] = $idempotencyKey;
        }

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $since,
            'since', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $until,
            'until', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $startingAfter,
            'starting_after', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $endingBefore,
            'ending_before', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $type,
            'type', // param base name
            'StatementType', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $termId,
            'term_id', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'application/problem+json', ],
            'application/json',
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem,
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (! empty($this->config->getUsername()) || ! (empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires Bearer authentication (access token)
        if (! empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        $defaultHeaders['X-Payjp-Client-User-Agent'] = Configuration::buildClientUserAgent();

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);

        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getStatement
     *
     * Get Statement
     *
     * @param  string $statementId statementId (required)
     * @param  string|null $idempotencyKey Idempotency key for the request
     *
     * @throws \PAYJPV2\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \PAYJPV2\Model\StatementResponse|\PAYJPV2\Model\ErrorResponse|\PAYJPV2\Model\ErrorResponse
     */
    public function getStatement($statementId, ?string $idempotencyKey = null)
    {
        list($response) = $this->getStatementWithHttpInfo($statementId, $idempotencyKey);

        return $response;
    }

    /**
     * Operation getStatementWithHttpInfo
     *
     * Get Statement
     *
     * @param  string $statementId (required)
     * @param  string|null $idempotencyKey Idempotency key for the request
     *
     * @throws \PAYJPV2\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \PAYJPV2\Model\StatementResponse|\PAYJPV2\Model\ErrorResponse|\PAYJPV2\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getStatementWithHttpInfo($statementId, ?string $idempotencyKey = null)
    {
        $request = $this->getStatementRequest($statementId, $idempotencyKey);

        try {
            $options = $this->createHttpClientOption();

            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch ($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\PAYJPV2\Model\StatementResponse',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\PAYJPV2\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\PAYJPV2\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }



            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\PAYJPV2\Model\StatementResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\PAYJPV2\Model\StatementResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);

                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\PAYJPV2\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);

                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\PAYJPV2\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);

                    throw $e;
            }


            throw $e;
        }
    }

    /**
     * Operation getStatementAsync
     *
     * Get Statement
     *
     * @param  string $statementId (required)
     * @param  string|null $idempotencyKey Idempotency key for the request
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getStatementAsync($statementId, ?string $idempotencyKey = null)
    {
        return $this->getStatementAsyncWithHttpInfo($statementId, $idempotencyKey)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getStatementAsyncWithHttpInfo
     *
     * Get Statement
     *
     * @param  string $statementId (required)
     * @param  string|null $idempotencyKey Idempotency key for the request
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getStatementAsyncWithHttpInfo($statementId, ?string $idempotencyKey = null)
    {
        $returnType = '\PAYJPV2\Model\StatementResponse';
        $request = $this->getStatementRequest($statementId, $idempotencyKey);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();

                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getStatement'
     *
     * @param  string $statementId (required)
     * @param  string|null $idempotencyKey Idempotency key for the request
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getStatementRequest($statementId, ?string $idempotencyKey = null)
    {

        // verify the required parameter 'statementId' is set
        if ($statementId === null || (is_array($statementId) && count($statementId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $statementId when calling getStatement'
            );
        }


        $resourcePath = '/v2/statements/{statement_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // idempotency key
        if ($idempotencyKey !== null) {
            $headerParams['Idempotency-Key'] = $idempotencyKey;
        }



        // path params
        if ($statementId !== null) {
            $resourcePath = str_replace(
                '{' . 'statement_id' . '}',
                ObjectSerializer::toPathValue($statementId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'application/problem+json', ],
            'application/json',
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem,
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (! empty($this->config->getUsername()) || ! (empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires Bearer authentication (access token)
        if (! empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        $defaultHeaders['X-Payjp-Client-User-Agent'] = Configuration::buildClientUserAgent();

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);

        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (! $options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders(),
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
