<?php
/**
 * CheckoutSessionCreateRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  PAYJPV2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PAY.JP v2 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PAYJPV2\Model;

use \ArrayAccess;
use \PAYJPV2\ObjectSerializer;

/**
 * CheckoutSessionCreateRequest Class Doc Comment
 *
 * @category Class
 * @package  PAYJPV2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CheckoutSessionCreateRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CheckoutSessionCreateRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'client_reference_id' => 'string',
        'customer' => 'string',
        'customer_email' => 'string',
        'customer_creation' => '\PAYJPV2\Model\CustomerCreation',
        'line_items' => '\PAYJPV2\Model\LineItemRequest[]',
        'mode' => '\PAYJPV2\Model\CheckoutSessionMode',
        'metadata' => 'array<string,\PAYJPV2\Model\MetadataValue>',
        'return_url' => 'string',
        'success_url' => 'string',
        'cancel_url' => 'string',
        'billing_address_collection' => '\PAYJPV2\Model\BillingAddressCollection',
        'currency' => '\PAYJPV2\Model\Currency',
        'expires_at' => '\DateTime',
        'locale' => '\PAYJPV2\Model\Locale',
        'payment_flow_data' => '\PAYJPV2\Model\PaymentFlowDataRequestInput',
        'payment_method_options' => '\PAYJPV2\Model\PaymentMethodOptionsRequest',
        'payment_method_types' => '\PAYJPV2\Model\PaymentMethodTypes[]',
        'setup_flow_data' => '\PAYJPV2\Model\SetupFlowDataRequest',
        'submit_type' => '\PAYJPV2\Model\CheckoutSessionSubmitType',
        'ui_mode' => '\PAYJPV2\Model\CheckoutSessionUIMode'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'client_reference_id' => null,
        'customer' => null,
        'customer_email' => 'email',
        'customer_creation' => null,
        'line_items' => null,
        'mode' => null,
        'metadata' => null,
        'return_url' => null,
        'success_url' => null,
        'cancel_url' => null,
        'billing_address_collection' => null,
        'currency' => null,
        'expires_at' => 'date-time',
        'locale' => null,
        'payment_flow_data' => null,
        'payment_method_options' => null,
        'payment_method_types' => null,
        'setup_flow_data' => null,
        'submit_type' => null,
        'ui_mode' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'client_reference_id' => false,
        'customer' => false,
        'customer_email' => false,
        'customer_creation' => false,
        'line_items' => false,
        'mode' => false,
        'metadata' => false,
        'return_url' => false,
        'success_url' => false,
        'cancel_url' => false,
        'billing_address_collection' => false,
        'currency' => false,
        'expires_at' => false,
        'locale' => false,
        'payment_flow_data' => false,
        'payment_method_options' => false,
        'payment_method_types' => false,
        'setup_flow_data' => false,
        'submit_type' => false,
        'ui_mode' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'client_reference_id' => 'client_reference_id',
        'customer' => 'customer',
        'customer_email' => 'customer_email',
        'customer_creation' => 'customer_creation',
        'line_items' => 'line_items',
        'mode' => 'mode',
        'metadata' => 'metadata',
        'return_url' => 'return_url',
        'success_url' => 'success_url',
        'cancel_url' => 'cancel_url',
        'billing_address_collection' => 'billing_address_collection',
        'currency' => 'currency',
        'expires_at' => 'expires_at',
        'locale' => 'locale',
        'payment_flow_data' => 'payment_flow_data',
        'payment_method_options' => 'payment_method_options',
        'payment_method_types' => 'payment_method_types',
        'setup_flow_data' => 'setup_flow_data',
        'submit_type' => 'submit_type',
        'ui_mode' => 'ui_mode'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'client_reference_id' => 'setClientReferenceId',
        'customer' => 'setCustomer',
        'customer_email' => 'setCustomerEmail',
        'customer_creation' => 'setCustomerCreation',
        'line_items' => 'setLineItems',
        'mode' => 'setMode',
        'metadata' => 'setMetadata',
        'return_url' => 'setReturnUrl',
        'success_url' => 'setSuccessUrl',
        'cancel_url' => 'setCancelUrl',
        'billing_address_collection' => 'setBillingAddressCollection',
        'currency' => 'setCurrency',
        'expires_at' => 'setExpiresAt',
        'locale' => 'setLocale',
        'payment_flow_data' => 'setPaymentFlowData',
        'payment_method_options' => 'setPaymentMethodOptions',
        'payment_method_types' => 'setPaymentMethodTypes',
        'setup_flow_data' => 'setSetupFlowData',
        'submit_type' => 'setSubmitType',
        'ui_mode' => 'setUiMode'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'client_reference_id' => 'getClientReferenceId',
        'customer' => 'getCustomer',
        'customer_email' => 'getCustomerEmail',
        'customer_creation' => 'getCustomerCreation',
        'line_items' => 'getLineItems',
        'mode' => 'getMode',
        'metadata' => 'getMetadata',
        'return_url' => 'getReturnUrl',
        'success_url' => 'getSuccessUrl',
        'cancel_url' => 'getCancelUrl',
        'billing_address_collection' => 'getBillingAddressCollection',
        'currency' => 'getCurrency',
        'expires_at' => 'getExpiresAt',
        'locale' => 'getLocale',
        'payment_flow_data' => 'getPaymentFlowData',
        'payment_method_options' => 'getPaymentMethodOptions',
        'payment_method_types' => 'getPaymentMethodTypes',
        'setup_flow_data' => 'getSetupFlowData',
        'submit_type' => 'getSubmitType',
        'ui_mode' => 'getUiMode'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('client_reference_id', $data ?? [], null);
        $this->setIfExists('customer', $data ?? [], null);
        $this->setIfExists('customer_email', $data ?? [], null);
        $this->setIfExists('customer_creation', $data ?? [], null);
        $this->setIfExists('line_items', $data ?? [], null);
        $this->setIfExists('mode', $data ?? [], null);
        $this->setIfExists('metadata', $data ?? [], null);
        $this->setIfExists('return_url', $data ?? [], null);
        $this->setIfExists('success_url', $data ?? [], null);
        $this->setIfExists('cancel_url', $data ?? [], null);
        $this->setIfExists('billing_address_collection', $data ?? [], null);
        $this->setIfExists('currency', $data ?? [], null);
        $this->setIfExists('expires_at', $data ?? [], null);
        $this->setIfExists('locale', $data ?? [], null);
        $this->setIfExists('payment_flow_data', $data ?? [], null);
        $this->setIfExists('payment_method_options', $data ?? [], null);
        $this->setIfExists('payment_method_types', $data ?? [], null);
        $this->setIfExists('setup_flow_data', $data ?? [], null);
        $this->setIfExists('submit_type', $data ?? [], null);
        $this->setIfExists('ui_mode', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['mode'] === null) {
            $invalidProperties[] = "'mode' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets client_reference_id
     *
     * @return string|null
     */
    public function getClientReferenceId()
    {
        return $this->container['client_reference_id'];
    }

    /**
     * Sets client_reference_id
     *
     * @param string|null $client_reference_id ID
     *
     * @return self
     */
    public function setClientReferenceId($client_reference_id)
    {
        if (is_null($client_reference_id)) {
            throw new \InvalidArgumentException('non-nullable client_reference_id cannot be null');
        }
        $this->container['client_reference_id'] = $client_reference_id;

        return $this;
    }

    /**
     * Gets customer
     *
     * @return string|null
     */
    public function getCustomer()
    {
        return $this->container['customer'];
    }

    /**
     * Sets customer
     *
     * @param string|null $customer 顧客ID
     *
     * @return self
     */
    public function setCustomer($customer)
    {
        if (is_null($customer)) {
            throw new \InvalidArgumentException('non-nullable customer cannot be null');
        }
        $this->container['customer'] = $customer;

        return $this;
    }

    /**
     * Gets customer_email
     *
     * @return string|null
     */
    public function getCustomerEmail()
    {
        return $this->container['customer_email'];
    }

    /**
     * Sets customer_email
     *
     * @param string|null $customer_email 顧客オブジェクトを作成する時に使われます。指定されていない場合、顧客にメールアドレスの入力を求めます。すでに顧客のメールアドレスを持っている場合は、このパラメータを使ってあらかじめ情報を入力しておくことが可能です。支払いが完了した後に顧客情報を取得したい場合は、customer属性を使用します。
     *
     * @return self
     */
    public function setCustomerEmail($customer_email)
    {
        if (is_null($customer_email)) {
            throw new \InvalidArgumentException('non-nullable customer_email cannot be null');
        }
        $this->container['customer_email'] = $customer_email;

        return $this;
    }

    /**
     * Gets customer_creation
     *
     * @return \PAYJPV2\Model\CustomerCreation|null
     */
    public function getCustomerCreation()
    {
        return $this->container['customer_creation'];
    }

    /**
     * Sets customer_creation
     *
     * @param \PAYJPV2\Model\CustomerCreation|null $customer_creation Checkout Session の確定時に Customer を作成するかどうかを指定します。<br> Customer が作成されない場合でも `customer_details` で Checkout に入力されたメールアドレス、住所、その他の顧客データを取得できます。<br> Customer を作成しない Session は、ダッシュボードでゲスト顧客としてグループ化されます。<br> `payment` および `setup` モードでのみ設定可能です。
     *
     * @return self
     */
    public function setCustomerCreation($customer_creation)
    {
        if (is_null($customer_creation)) {
            throw new \InvalidArgumentException('non-nullable customer_creation cannot be null');
        }
        $this->container['customer_creation'] = $customer_creation;

        return $this;
    }

    /**
     * Gets line_items
     *
     * @return \PAYJPV2\Model\LineItemRequest[]|null
     */
    public function getLineItems()
    {
        return $this->container['line_items'];
    }

    /**
     * Sets line_items
     *
     * @param \PAYJPV2\Model\LineItemRequest[]|null $line_items 顧客が購入する商品のリストです。このパラメータを使用して、1回限りまたは定期的な料金を渡します。  `payment` モードの場合、最大100個のラインアイテムを使用できます。 <!-- `subscription` モードの場合、定期的な料金のラインアイテムは最大20個、1回限りの料金のラインアイテムは最大20個です。1回限りの料金のラインアイテムは、最初の請求書にのみ記載されます。 -->
     *
     * @return self
     */
    public function setLineItems($line_items)
    {
        if (is_null($line_items)) {
            throw new \InvalidArgumentException('non-nullable line_items cannot be null');
        }
        $this->container['line_items'] = $line_items;

        return $this;
    }

    /**
     * Gets mode
     *
     * @return \PAYJPV2\Model\CheckoutSessionMode
     */
    public function getMode()
    {
        return $this->container['mode'];
    }

    /**
     * Sets mode
     *
     * @param \PAYJPV2\Model\CheckoutSessionMode $mode Checkout Session のモード  | 指定できる値 | |:---| | **hosted**: PAY.JPでホスティングしている画面を使用します。 |
     *
     * @return self
     */
    public function setMode($mode)
    {
        if (is_null($mode)) {
            throw new \InvalidArgumentException('non-nullable mode cannot be null');
        }
        $this->container['mode'] = $mode;

        return $this;
    }

    /**
     * Gets metadata
     *
     * @return array<string,\PAYJPV2\Model\MetadataValue>|null
     */
    public function getMetadata()
    {
        return $this->container['metadata'];
    }

    /**
     * Sets metadata
     *
     * @param array<string,\PAYJPV2\Model\MetadataValue>|null $metadata キーバリューの任意のデータを格納できます。<a href=\"https://docs.pay.jp/v2/metadata\">詳細はメタデータのドキュメントを参照してください。</a>
     *
     * @return self
     */
    public function setMetadata($metadata)
    {
        if (is_null($metadata)) {
            throw new \InvalidArgumentException('non-nullable metadata cannot be null');
        }
        $this->container['metadata'] = $metadata;

        return $this;
    }

    /**
     * Gets return_url
     *
     * @return string|null
     */
    public function getReturnUrl()
    {
        return $this->container['return_url'];
    }

    /**
     * Sets return_url
     *
     * @param string|null $return_url 顧客が支払いを行うか、支払いをキャンセルした後にリダイレクトする URL です。
     *
     * @return self
     */
    public function setReturnUrl($return_url)
    {
        if (is_null($return_url)) {
            throw new \InvalidArgumentException('non-nullable return_url cannot be null');
        }
        $this->container['return_url'] = $return_url;

        return $this;
    }

    /**
     * Gets success_url
     *
     * @return string|null
     */
    public function getSuccessUrl()
    {
        return $this->container['success_url'];
    }

    /**
     * Sets success_url
     *
     * @param string|null $success_url 支払いや設定が完了した際に、PAY.JP が顧客をリダイレクトするURL。成功したCheckout Sessionからの情報をページで使用したい場合は、成功ページのカスタマイズに関するガイドをお読みください。
     *
     * @return self
     */
    public function setSuccessUrl($success_url)
    {
        if (is_null($success_url)) {
            throw new \InvalidArgumentException('non-nullable success_url cannot be null');
        }
        $this->container['success_url'] = $success_url;

        return $this;
    }

    /**
     * Gets cancel_url
     *
     * @return string|null
     */
    public function getCancelUrl()
    {
        return $this->container['cancel_url'];
    }

    /**
     * Sets cancel_url
     *
     * @param string|null $cancel_url キャンセル時のリダイレクトURL
     *
     * @return self
     */
    public function setCancelUrl($cancel_url)
    {
        if (is_null($cancel_url)) {
            throw new \InvalidArgumentException('non-nullable cancel_url cannot be null');
        }
        $this->container['cancel_url'] = $cancel_url;

        return $this;
    }

    /**
     * Gets billing_address_collection
     *
     * @return \PAYJPV2\Model\BillingAddressCollection|null
     */
    public function getBillingAddressCollection()
    {
        return $this->container['billing_address_collection'];
    }

    /**
     * Sets billing_address_collection
     *
     * @param \PAYJPV2\Model\BillingAddressCollection|null $billing_address_collection Checkout で顧客の請求先住所を収集するかどうかを指定します。デフォルトは `auto` です。  | 指定できる値 | |:---| | **auto**: 請求先住所が必要と判断した場合に入力欄が表示されます。 | | **required**: 常に請求先住所の入力欄が表示されまうs。 |
     *
     * @return self
     */
    public function setBillingAddressCollection($billing_address_collection)
    {
        if (is_null($billing_address_collection)) {
            throw new \InvalidArgumentException('non-nullable billing_address_collection cannot be null');
        }
        $this->container['billing_address_collection'] = $billing_address_collection;

        return $this;
    }

    /**
     * Gets currency
     *
     * @return \PAYJPV2\Model\Currency|null
     */
    public function getCurrency()
    {
        return $this->container['currency'];
    }

    /**
     * Sets currency
     *
     * @param \PAYJPV2\Model\Currency|null $currency 価格の通貨。現在は `jpy` のみサポートしています。
     *
     * @return self
     */
    public function setCurrency($currency)
    {
        if (is_null($currency)) {
            throw new \InvalidArgumentException('non-nullable currency cannot be null');
        }
        $this->container['currency'] = $currency;

        return $this;
    }

    /**
     * Gets expires_at
     *
     * @return \DateTime|null
     */
    public function getExpiresAt()
    {
        return $this->container['expires_at'];
    }

    /**
     * Sets expires_at
     *
     * @param \DateTime|null $expires_at Checkout Session の有効期限が失効する日時。
     *
     * @return self
     */
    public function setExpiresAt($expires_at)
    {
        if (is_null($expires_at)) {
            throw new \InvalidArgumentException('non-nullable expires_at cannot be null');
        }
        $this->container['expires_at'] = $expires_at;

        return $this;
    }

    /**
     * Gets locale
     *
     * @return \PAYJPV2\Model\Locale|null
     */
    public function getLocale()
    {
        return $this->container['locale'];
    }

    /**
     * Sets locale
     *
     * @param \PAYJPV2\Model\Locale|null $locale Checkout 画面の表示言語を指定します。  | 指定できる値 | |:---| | **ja**: 日本語で表示します。 |
     *
     * @return self
     */
    public function setLocale($locale)
    {
        if (is_null($locale)) {
            throw new \InvalidArgumentException('non-nullable locale cannot be null');
        }
        $this->container['locale'] = $locale;

        return $this;
    }

    /**
     * Gets payment_flow_data
     *
     * @return \PAYJPV2\Model\PaymentFlowDataRequestInput|null
     */
    public function getPaymentFlowData()
    {
        return $this->container['payment_flow_data'];
    }

    /**
     * Sets payment_flow_data
     *
     * @param \PAYJPV2\Model\PaymentFlowDataRequestInput|null $payment_flow_data `payment` モード指定時に PaymentFlow 作成に使用するパラメーター。
     *
     * @return self
     */
    public function setPaymentFlowData($payment_flow_data)
    {
        if (is_null($payment_flow_data)) {
            throw new \InvalidArgumentException('non-nullable payment_flow_data cannot be null');
        }
        $this->container['payment_flow_data'] = $payment_flow_data;

        return $this;
    }

    /**
     * Gets payment_method_options
     *
     * @return \PAYJPV2\Model\PaymentMethodOptionsRequest|null
     */
    public function getPaymentMethodOptions()
    {
        return $this->container['payment_method_options'];
    }

    /**
     * Sets payment_method_options
     *
     * @param \PAYJPV2\Model\PaymentMethodOptionsRequest|null $payment_method_options この PaymentFlow の支払い方法の個別設定。
     *
     * @return self
     */
    public function setPaymentMethodOptions($payment_method_options)
    {
        if (is_null($payment_method_options)) {
            throw new \InvalidArgumentException('non-nullable payment_method_options cannot be null');
        }
        $this->container['payment_method_options'] = $payment_method_options;

        return $this;
    }

    /**
     * Gets payment_method_types
     *
     * @return \PAYJPV2\Model\PaymentMethodTypes[]|null
     */
    public function getPaymentMethodTypes()
    {
        return $this->container['payment_method_types'];
    }

    /**
     * Sets payment_method_types
     *
     * @param \PAYJPV2\Model\PaymentMethodTypes[]|null $payment_method_types この PaymentFlow で使用できる支払い方法の種類（カードなど）のリストです。 指定しない場合、ダッシュボードで利用可能な状態にしている支払い方法を自動的に表示します。
     *
     * @return self
     */
    public function setPaymentMethodTypes($payment_method_types)
    {
        if (is_null($payment_method_types)) {
            throw new \InvalidArgumentException('non-nullable payment_method_types cannot be null');
        }
        $this->container['payment_method_types'] = $payment_method_types;

        return $this;
    }

    /**
     * Gets setup_flow_data
     *
     * @return \PAYJPV2\Model\SetupFlowDataRequest|null
     */
    public function getSetupFlowData()
    {
        return $this->container['setup_flow_data'];
    }

    /**
     * Sets setup_flow_data
     *
     * @param \PAYJPV2\Model\SetupFlowDataRequest|null $setup_flow_data `setup` モードの Checkout Session を作成する際、SetupFlow の作成に渡されるパラメーター
     *
     * @return self
     */
    public function setSetupFlowData($setup_flow_data)
    {
        if (is_null($setup_flow_data)) {
            throw new \InvalidArgumentException('non-nullable setup_flow_data cannot be null');
        }
        $this->container['setup_flow_data'] = $setup_flow_data;

        return $this;
    }

    /**
     * Gets submit_type
     *
     * @return \PAYJPV2\Model\CheckoutSessionSubmitType|null
     */
    public function getSubmitType()
    {
        return $this->container['submit_type'];
    }

    /**
     * Sets submit_type
     *
     * @param \PAYJPV2\Model\CheckoutSessionSubmitType|null $submit_type Checkout の画面上に表示される送信ボタンなど、ページ上の関連テキストをカスタマイズするために使用されます。<br> `submit_type` は、`payment` モードの Checkout Session でのみ指定できます。未指定時、あるいは `auto` の場合、`pay` が使用されます。  | 指定できる値 | |:---| | **auto**: `pay` が使用されます。 | | **pay**: 「支払う」（デフォルト） | | **book**: 「予約する」 | | **donate**: 「寄付する」 |
     *
     * @return self
     */
    public function setSubmitType($submit_type)
    {
        if (is_null($submit_type)) {
            throw new \InvalidArgumentException('non-nullable submit_type cannot be null');
        }
        $this->container['submit_type'] = $submit_type;

        return $this;
    }

    /**
     * Gets ui_mode
     *
     * @return \PAYJPV2\Model\CheckoutSessionUIMode|null
     */
    public function getUiMode()
    {
        return $this->container['ui_mode'];
    }

    /**
     * Sets ui_mode
     *
     * @param \PAYJPV2\Model\CheckoutSessionUIMode|null $ui_mode Checkout Session の UI モード。デフォルトは `hosted` です。<br>  | 指定できる値 | |:---| | **hosted**: PAY.JPでホスティングしている画面を使用します。 |
     *
     * @return self
     */
    public function setUiMode($ui_mode)
    {
        if (is_null($ui_mode)) {
            throw new \InvalidArgumentException('non-nullable ui_mode cannot be null');
        }
        $this->container['ui_mode'] = $ui_mode;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


