<?php
/**
 * CheckoutSessionDetailsResponse
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  PAYJPV2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PAY.JP v2 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PAYJPV2\Model;

use \ArrayAccess;
use \PAYJPV2\ObjectSerializer;

/**
 * CheckoutSessionDetailsResponse Class Doc Comment
 *
 * @category Class
 * @package  PAYJPV2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CheckoutSessionDetailsResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CheckoutSessionDetailsResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'object' => 'string',
        'livemode' => 'bool',
        'amount_subtotal' => 'int',
        'amount_total' => 'int',
        'billing_address_collection' => '\PAYJPV2\Model\BillingAddressCollection',
        'cancel_url' => 'string',
        'customer' => '\PAYJPV2\Model\Customer',
        'customer_email' => 'string',
        'customer_details' => 'array<string,mixed>',
        'expires_at' => '\DateTime',
        'currency' => '\PAYJPV2\Model\Currency',
        'locale' => '\PAYJPV2\Model\Locale',
        'payment_flow' => '\PAYJPV2\Model\PaymentFlow',
        'payment_method_types' => '\PAYJPV2\Model\PaymentMethodTypes[]',
        'payment_method_options' => 'array<string,mixed>',
        'setup_flow' => '\PAYJPV2\Model\PaymentFlowDataRequestOutput',
        'submit_type' => '\PAYJPV2\Model\CheckoutSessionSubmitType',
        'mode' => '\PAYJPV2\Model\CheckoutSessionMode',
        'ui_mode' => '\PAYJPV2\Model\CheckoutSessionUIMode',
        'created_at' => '\DateTime',
        'updated_at' => '\DateTime',
        'metadata' => 'array<string,\PAYJPV2\Model\MetadataValue>',
        'status' => '\PAYJPV2\Model\CheckoutSessionStatus',
        'line_items' => '\PAYJPV2\Model\CheckoutSessionLineItemsResponse',
        'success_url' => 'string',
        'url' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'object' => null,
        'livemode' => null,
        'amount_subtotal' => null,
        'amount_total' => null,
        'billing_address_collection' => null,
        'cancel_url' => null,
        'customer' => null,
        'customer_email' => null,
        'customer_details' => null,
        'expires_at' => 'date-time',
        'currency' => null,
        'locale' => null,
        'payment_flow' => null,
        'payment_method_types' => null,
        'payment_method_options' => null,
        'setup_flow' => null,
        'submit_type' => null,
        'mode' => null,
        'ui_mode' => null,
        'created_at' => 'date-time',
        'updated_at' => 'date-time',
        'metadata' => null,
        'status' => null,
        'line_items' => null,
        'success_url' => null,
        'url' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'object' => false,
        'livemode' => false,
        'amount_subtotal' => true,
        'amount_total' => true,
        'billing_address_collection' => true,
        'cancel_url' => true,
        'customer' => true,
        'customer_email' => true,
        'customer_details' => false,
        'expires_at' => true,
        'currency' => false,
        'locale' => true,
        'payment_flow' => true,
        'payment_method_types' => true,
        'payment_method_options' => true,
        'setup_flow' => true,
        'submit_type' => true,
        'mode' => false,
        'ui_mode' => false,
        'created_at' => false,
        'updated_at' => false,
        'metadata' => false,
        'status' => false,
        'line_items' => true,
        'success_url' => true,
        'url' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'object' => 'object',
        'livemode' => 'livemode',
        'amount_subtotal' => 'amount_subtotal',
        'amount_total' => 'amount_total',
        'billing_address_collection' => 'billing_address_collection',
        'cancel_url' => 'cancel_url',
        'customer' => 'customer',
        'customer_email' => 'customer_email',
        'customer_details' => 'customer_details',
        'expires_at' => 'expires_at',
        'currency' => 'currency',
        'locale' => 'locale',
        'payment_flow' => 'payment_flow',
        'payment_method_types' => 'payment_method_types',
        'payment_method_options' => 'payment_method_options',
        'setup_flow' => 'setup_flow',
        'submit_type' => 'submit_type',
        'mode' => 'mode',
        'ui_mode' => 'ui_mode',
        'created_at' => 'created_at',
        'updated_at' => 'updated_at',
        'metadata' => 'metadata',
        'status' => 'status',
        'line_items' => 'line_items',
        'success_url' => 'success_url',
        'url' => 'url'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'object' => 'setObject',
        'livemode' => 'setLivemode',
        'amount_subtotal' => 'setAmountSubtotal',
        'amount_total' => 'setAmountTotal',
        'billing_address_collection' => 'setBillingAddressCollection',
        'cancel_url' => 'setCancelUrl',
        'customer' => 'setCustomer',
        'customer_email' => 'setCustomerEmail',
        'customer_details' => 'setCustomerDetails',
        'expires_at' => 'setExpiresAt',
        'currency' => 'setCurrency',
        'locale' => 'setLocale',
        'payment_flow' => 'setPaymentFlow',
        'payment_method_types' => 'setPaymentMethodTypes',
        'payment_method_options' => 'setPaymentMethodOptions',
        'setup_flow' => 'setSetupFlow',
        'submit_type' => 'setSubmitType',
        'mode' => 'setMode',
        'ui_mode' => 'setUiMode',
        'created_at' => 'setCreatedAt',
        'updated_at' => 'setUpdatedAt',
        'metadata' => 'setMetadata',
        'status' => 'setStatus',
        'line_items' => 'setLineItems',
        'success_url' => 'setSuccessUrl',
        'url' => 'setUrl'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'object' => 'getObject',
        'livemode' => 'getLivemode',
        'amount_subtotal' => 'getAmountSubtotal',
        'amount_total' => 'getAmountTotal',
        'billing_address_collection' => 'getBillingAddressCollection',
        'cancel_url' => 'getCancelUrl',
        'customer' => 'getCustomer',
        'customer_email' => 'getCustomerEmail',
        'customer_details' => 'getCustomerDetails',
        'expires_at' => 'getExpiresAt',
        'currency' => 'getCurrency',
        'locale' => 'getLocale',
        'payment_flow' => 'getPaymentFlow',
        'payment_method_types' => 'getPaymentMethodTypes',
        'payment_method_options' => 'getPaymentMethodOptions',
        'setup_flow' => 'getSetupFlow',
        'submit_type' => 'getSubmitType',
        'mode' => 'getMode',
        'ui_mode' => 'getUiMode',
        'created_at' => 'getCreatedAt',
        'updated_at' => 'getUpdatedAt',
        'metadata' => 'getMetadata',
        'status' => 'getStatus',
        'line_items' => 'getLineItems',
        'success_url' => 'getSuccessUrl',
        'url' => 'getUrl'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const OBJECT_CHECKOUT_SESSION = 'checkout.session';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getObjectAllowableValues()
    {
        return [
            self::OBJECT_CHECKOUT_SESSION,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('object', $data ?? [], 'checkout.session');
        $this->setIfExists('livemode', $data ?? [], null);
        $this->setIfExists('amount_subtotal', $data ?? [], null);
        $this->setIfExists('amount_total', $data ?? [], null);
        $this->setIfExists('billing_address_collection', $data ?? [], null);
        $this->setIfExists('cancel_url', $data ?? [], null);
        $this->setIfExists('customer', $data ?? [], null);
        $this->setIfExists('customer_email', $data ?? [], null);
        $this->setIfExists('customer_details', $data ?? [], null);
        $this->setIfExists('expires_at', $data ?? [], null);
        $this->setIfExists('currency', $data ?? [], null);
        $this->setIfExists('locale', $data ?? [], null);
        $this->setIfExists('payment_flow', $data ?? [], null);
        $this->setIfExists('payment_method_types', $data ?? [], null);
        $this->setIfExists('payment_method_options', $data ?? [], null);
        $this->setIfExists('setup_flow', $data ?? [], null);
        $this->setIfExists('submit_type', $data ?? [], null);
        $this->setIfExists('mode', $data ?? [], null);
        $this->setIfExists('ui_mode', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('updated_at', $data ?? [], null);
        $this->setIfExists('metadata', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('line_items', $data ?? [], null);
        $this->setIfExists('success_url', $data ?? [], null);
        $this->setIfExists('url', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getObjectAllowableValues();
        if (!is_null($this->container['object']) && !in_array($this->container['object'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'object', must be one of '%s'",
                $this->container['object'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id ID
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets object
     *
     * @return string|null
     */
    public function getObject()
    {
        return $this->container['object'];
    }

    /**
     * Sets object
     *
     * @param string|null $object object
     *
     * @return self
     */
    public function setObject($object)
    {
        if (is_null($object)) {
            throw new \InvalidArgumentException('non-nullable object cannot be null');
        }
        $allowedValues = $this->getObjectAllowableValues();
        if (!in_array($object, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'object', must be one of '%s'",
                    $object,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['object'] = $object;

        return $this;
    }

    /**
     * Gets livemode
     *
     * @return bool|null
     */
    public function getLivemode()
    {
        return $this->container['livemode'];
    }

    /**
     * Sets livemode
     *
     * @param bool|null $livemode 本番環境かどうか
     *
     * @return self
     */
    public function setLivemode($livemode)
    {
        if (is_null($livemode)) {
            throw new \InvalidArgumentException('non-nullable livemode cannot be null');
        }
        $this->container['livemode'] = $livemode;

        return $this;
    }

    /**
     * Gets amount_subtotal
     *
     * @return int|null
     */
    public function getAmountSubtotal()
    {
        return $this->container['amount_subtotal'];
    }

    /**
     * Sets amount_subtotal
     *
     * @param int|null $amount_subtotal amount_subtotal
     *
     * @return self
     */
    public function setAmountSubtotal($amount_subtotal)
    {
        if (is_null($amount_subtotal)) {
            array_push($this->openAPINullablesSetToNull, 'amount_subtotal');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('amount_subtotal', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['amount_subtotal'] = $amount_subtotal;

        return $this;
    }

    /**
     * Gets amount_total
     *
     * @return int|null
     */
    public function getAmountTotal()
    {
        return $this->container['amount_total'];
    }

    /**
     * Sets amount_total
     *
     * @param int|null $amount_total amount_total
     *
     * @return self
     */
    public function setAmountTotal($amount_total)
    {
        if (is_null($amount_total)) {
            array_push($this->openAPINullablesSetToNull, 'amount_total');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('amount_total', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['amount_total'] = $amount_total;

        return $this;
    }

    /**
     * Gets billing_address_collection
     *
     * @return \PAYJPV2\Model\BillingAddressCollection|null
     */
    public function getBillingAddressCollection()
    {
        return $this->container['billing_address_collection'];
    }

    /**
     * Sets billing_address_collection
     *
     * @param \PAYJPV2\Model\BillingAddressCollection|null $billing_address_collection billing_address_collection
     *
     * @return self
     */
    public function setBillingAddressCollection($billing_address_collection)
    {
        if (is_null($billing_address_collection)) {
            array_push($this->openAPINullablesSetToNull, 'billing_address_collection');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('billing_address_collection', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['billing_address_collection'] = $billing_address_collection;

        return $this;
    }

    /**
     * Gets cancel_url
     *
     * @return string|null
     */
    public function getCancelUrl()
    {
        return $this->container['cancel_url'];
    }

    /**
     * Sets cancel_url
     *
     * @param string|null $cancel_url cancel_url
     *
     * @return self
     */
    public function setCancelUrl($cancel_url)
    {
        if (is_null($cancel_url)) {
            array_push($this->openAPINullablesSetToNull, 'cancel_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('cancel_url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['cancel_url'] = $cancel_url;

        return $this;
    }

    /**
     * Gets customer
     *
     * @return \PAYJPV2\Model\Customer|null
     */
    public function getCustomer()
    {
        return $this->container['customer'];
    }

    /**
     * Sets customer
     *
     * @param \PAYJPV2\Model\Customer|null $customer customer
     *
     * @return self
     */
    public function setCustomer($customer)
    {
        if (is_null($customer)) {
            array_push($this->openAPINullablesSetToNull, 'customer');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('customer', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['customer'] = $customer;

        return $this;
    }

    /**
     * Gets customer_email
     *
     * @return string|null
     */
    public function getCustomerEmail()
    {
        return $this->container['customer_email'];
    }

    /**
     * Sets customer_email
     *
     * @param string|null $customer_email customer_email
     *
     * @return self
     */
    public function setCustomerEmail($customer_email)
    {
        if (is_null($customer_email)) {
            array_push($this->openAPINullablesSetToNull, 'customer_email');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('customer_email', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['customer_email'] = $customer_email;

        return $this;
    }

    /**
     * Gets customer_details
     *
     * @return array<string,mixed>|null
     */
    public function getCustomerDetails()
    {
        return $this->container['customer_details'];
    }

    /**
     * Sets customer_details
     *
     * @param array<string,mixed>|null $customer_details `expand` パラメーターを指定した場合、顧客の詳細情報を含んだオブジェクトが返却されます。  | 説明 | |:---| | **email**: 顧客のメールアドレス |
     *
     * @return self
     */
    public function setCustomerDetails($customer_details)
    {
        if (is_null($customer_details)) {
            throw new \InvalidArgumentException('non-nullable customer_details cannot be null');
        }
        $this->container['customer_details'] = $customer_details;

        return $this;
    }

    /**
     * Gets expires_at
     *
     * @return \DateTime|null
     */
    public function getExpiresAt()
    {
        return $this->container['expires_at'];
    }

    /**
     * Sets expires_at
     *
     * @param \DateTime|null $expires_at expires_at
     *
     * @return self
     */
    public function setExpiresAt($expires_at)
    {
        if (is_null($expires_at)) {
            array_push($this->openAPINullablesSetToNull, 'expires_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('expires_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['expires_at'] = $expires_at;

        return $this;
    }

    /**
     * Gets currency
     *
     * @return \PAYJPV2\Model\Currency|null
     */
    public function getCurrency()
    {
        return $this->container['currency'];
    }

    /**
     * Sets currency
     *
     * @param \PAYJPV2\Model\Currency|null $currency 価格の通貨。現在は `jpy` のみサポートしています。
     *
     * @return self
     */
    public function setCurrency($currency)
    {
        if (is_null($currency)) {
            throw new \InvalidArgumentException('non-nullable currency cannot be null');
        }
        $this->container['currency'] = $currency;

        return $this;
    }

    /**
     * Gets locale
     *
     * @return \PAYJPV2\Model\Locale|null
     */
    public function getLocale()
    {
        return $this->container['locale'];
    }

    /**
     * Sets locale
     *
     * @param \PAYJPV2\Model\Locale|null $locale locale
     *
     * @return self
     */
    public function setLocale($locale)
    {
        if (is_null($locale)) {
            array_push($this->openAPINullablesSetToNull, 'locale');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('locale', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['locale'] = $locale;

        return $this;
    }

    /**
     * Gets payment_flow
     *
     * @return \PAYJPV2\Model\PaymentFlow|null
     */
    public function getPaymentFlow()
    {
        return $this->container['payment_flow'];
    }

    /**
     * Sets payment_flow
     *
     * @param \PAYJPV2\Model\PaymentFlow|null $payment_flow payment_flow
     *
     * @return self
     */
    public function setPaymentFlow($payment_flow)
    {
        if (is_null($payment_flow)) {
            array_push($this->openAPINullablesSetToNull, 'payment_flow');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('payment_flow', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['payment_flow'] = $payment_flow;

        return $this;
    }

    /**
     * Gets payment_method_types
     *
     * @return \PAYJPV2\Model\PaymentMethodTypes[]|null
     */
    public function getPaymentMethodTypes()
    {
        return $this->container['payment_method_types'];
    }

    /**
     * Sets payment_method_types
     *
     * @param \PAYJPV2\Model\PaymentMethodTypes[]|null $payment_method_types payment_method_types
     *
     * @return self
     */
    public function setPaymentMethodTypes($payment_method_types)
    {
        if (is_null($payment_method_types)) {
            array_push($this->openAPINullablesSetToNull, 'payment_method_types');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('payment_method_types', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['payment_method_types'] = $payment_method_types;

        return $this;
    }

    /**
     * Gets payment_method_options
     *
     * @return array<string,mixed>|null
     */
    public function getPaymentMethodOptions()
    {
        return $this->container['payment_method_options'];
    }

    /**
     * Sets payment_method_options
     *
     * @param array<string,mixed>|null $payment_method_options payment_method_options
     *
     * @return self
     */
    public function setPaymentMethodOptions($payment_method_options)
    {
        if (is_null($payment_method_options)) {
            array_push($this->openAPINullablesSetToNull, 'payment_method_options');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('payment_method_options', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['payment_method_options'] = $payment_method_options;

        return $this;
    }

    /**
     * Gets setup_flow
     *
     * @return \PAYJPV2\Model\PaymentFlowDataRequestOutput|null
     */
    public function getSetupFlow()
    {
        return $this->container['setup_flow'];
    }

    /**
     * Sets setup_flow
     *
     * @param \PAYJPV2\Model\PaymentFlowDataRequestOutput|null $setup_flow setup_flow
     *
     * @return self
     */
    public function setSetupFlow($setup_flow)
    {
        if (is_null($setup_flow)) {
            array_push($this->openAPINullablesSetToNull, 'setup_flow');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('setup_flow', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['setup_flow'] = $setup_flow;

        return $this;
    }

    /**
     * Gets submit_type
     *
     * @return \PAYJPV2\Model\CheckoutSessionSubmitType|null
     */
    public function getSubmitType()
    {
        return $this->container['submit_type'];
    }

    /**
     * Sets submit_type
     *
     * @param \PAYJPV2\Model\CheckoutSessionSubmitType|null $submit_type submit_type
     *
     * @return self
     */
    public function setSubmitType($submit_type)
    {
        if (is_null($submit_type)) {
            array_push($this->openAPINullablesSetToNull, 'submit_type');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('submit_type', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['submit_type'] = $submit_type;

        return $this;
    }

    /**
     * Gets mode
     *
     * @return \PAYJPV2\Model\CheckoutSessionMode|null
     */
    public function getMode()
    {
        return $this->container['mode'];
    }

    /**
     * Sets mode
     *
     * @param \PAYJPV2\Model\CheckoutSessionMode|null $mode Checkout Session のモード  | 指定できる値 | |:---| | **hosted**: PAY.JPでホスティングしている画面を使用します。 |
     *
     * @return self
     */
    public function setMode($mode)
    {
        if (is_null($mode)) {
            throw new \InvalidArgumentException('non-nullable mode cannot be null');
        }
        $this->container['mode'] = $mode;

        return $this;
    }

    /**
     * Gets ui_mode
     *
     * @return \PAYJPV2\Model\CheckoutSessionUIMode|null
     */
    public function getUiMode()
    {
        return $this->container['ui_mode'];
    }

    /**
     * Sets ui_mode
     *
     * @param \PAYJPV2\Model\CheckoutSessionUIMode|null $ui_mode Checkout Session の UI モード。デフォルトは `hosted` です。<br>  | 指定できる値 | |:---| | **hosted**: PAY.JPでホスティングしている画面を使用します。 |
     *
     * @return self
     */
    public function setUiMode($ui_mode)
    {
        if (is_null($ui_mode)) {
            throw new \InvalidArgumentException('non-nullable ui_mode cannot be null');
        }
        $this->container['ui_mode'] = $ui_mode;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return \DateTime|null
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param \DateTime|null $created_at 作成日時 (UTC, ISO 8601 形式)
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            throw new \InvalidArgumentException('non-nullable created_at cannot be null');
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets updated_at
     *
     * @return \DateTime|null
     */
    public function getUpdatedAt()
    {
        return $this->container['updated_at'];
    }

    /**
     * Sets updated_at
     *
     * @param \DateTime|null $updated_at 更新日時 (UTC, ISO 8601 形式)
     *
     * @return self
     */
    public function setUpdatedAt($updated_at)
    {
        if (is_null($updated_at)) {
            throw new \InvalidArgumentException('non-nullable updated_at cannot be null');
        }
        $this->container['updated_at'] = $updated_at;

        return $this;
    }

    /**
     * Gets metadata
     *
     * @return array<string,\PAYJPV2\Model\MetadataValue>|null
     */
    public function getMetadata()
    {
        return $this->container['metadata'];
    }

    /**
     * Sets metadata
     *
     * @param array<string,\PAYJPV2\Model\MetadataValue>|null $metadata メタデータ
     *
     * @return self
     */
    public function setMetadata($metadata)
    {
        if (is_null($metadata)) {
            throw new \InvalidArgumentException('non-nullable metadata cannot be null');
        }
        $this->container['metadata'] = $metadata;

        return $this;
    }

    /**
     * Gets status
     *
     * @return \PAYJPV2\Model\CheckoutSessionStatus|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param \PAYJPV2\Model\CheckoutSessionStatus|null $status チェックアウトセッションのステータス
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets line_items
     *
     * @return \PAYJPV2\Model\CheckoutSessionLineItemsResponse|null
     */
    public function getLineItems()
    {
        return $this->container['line_items'];
    }

    /**
     * Sets line_items
     *
     * @param \PAYJPV2\Model\CheckoutSessionLineItemsResponse|null $line_items line_items
     *
     * @return self
     */
    public function setLineItems($line_items)
    {
        if (is_null($line_items)) {
            array_push($this->openAPINullablesSetToNull, 'line_items');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('line_items', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['line_items'] = $line_items;

        return $this;
    }

    /**
     * Gets success_url
     *
     * @return string|null
     */
    public function getSuccessUrl()
    {
        return $this->container['success_url'];
    }

    /**
     * Sets success_url
     *
     * @param string|null $success_url success_url
     *
     * @return self
     */
    public function setSuccessUrl($success_url)
    {
        if (is_null($success_url)) {
            array_push($this->openAPINullablesSetToNull, 'success_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('success_url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['success_url'] = $success_url;

        return $this;
    }

    /**
     * Gets url
     *
     * @return string|null
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string|null $url URL
     *
     * @return self
     */
    public function setUrl($url)
    {
        if (is_null($url)) {
            throw new \InvalidArgumentException('non-nullable url cannot be null');
        }
        $this->container['url'] = $url;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


