<?php

/**
 * PaymentMethodConfigurationDetailsResponse
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  PAYJPV2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PAY.JP API v2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PAYJPV2\Model;

use ArrayAccess;
use PAYJPV2\ObjectSerializer;

/**
 * PaymentMethodConfigurationDetailsResponse Class Doc Comment
 *
 * @category Class
 * @package  PAYJPV2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PaymentMethodConfigurationDetailsResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'PaymentMethodConfigurationDetailsResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'object' => 'string',
        'id' => 'string',
        'livemode' => 'bool',
        'active' => 'bool',
        'name' => 'string',
        'paypay' => '\PAYJPV2\Model\PaymentMethodConfigurationSettingResponse',
        'card' => '\PAYJPV2\Model\PaymentMethodConfigurationSettingResponse',
        'applePay' => '\PAYJPV2\Model\PaymentMethodConfigurationSettingResponse',
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'object' => null,
        'id' => null,
        'livemode' => null,
        'active' => null,
        'name' => null,
        'paypay' => null,
        'card' => null,
        'applePay' => null,
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var bool[]
      */
    protected static array $openAPINullables = [
        'object' => false,
        'id' => false,
        'livemode' => false,
        'active' => false,
        'name' => true,
        'paypay' => false,
        'card' => false,
        'applePay' => false,
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var bool[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return bool[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param bool[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'object' => 'object',
        'id' => 'id',
        'livemode' => 'livemode',
        'active' => 'active',
        'name' => 'name',
        'paypay' => 'paypay',
        'card' => 'card',
        'applePay' => 'apple_pay',
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'object' => 'setObject',
        'id' => 'setId',
        'livemode' => 'setLivemode',
        'active' => 'setActive',
        'name' => 'setName',
        'paypay' => 'setPaypay',
        'card' => 'setCard',
        'applePay' => 'setApplePay',
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'object' => 'getObject',
        'id' => 'getId',
        'livemode' => 'getLivemode',
        'active' => 'getActive',
        'name' => 'getName',
        'paypay' => 'getPaypay',
        'card' => 'getCard',
        'applePay' => 'getApplePay',
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const OBJECT_PAYMENT_METHOD_CONFIGURATION = 'payment_method_configuration';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getObjectAllowableValues()
    {
        return [
            self::OBJECT_PAYMENT_METHOD_CONFIGURATION,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('object', $data ?? [], 'payment_method_configuration');
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('livemode', $data ?? [], null);
        $this->setIfExists('active', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('paypay', $data ?? [], null);
        $this->setIfExists('card', $data ?? [], null);
        $this->setIfExists('applePay', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getObjectAllowableValues();
        if (! is_null($this->container['object']) && ! in_array($this->container['object'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'object', must be one of '%s'",
                $this->container['object'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['livemode'] === null) {
            $invalidProperties[] = "'livemode' can't be null";
        }
        if ($this->container['active'] === null) {
            $invalidProperties[] = "'active' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['paypay'] === null) {
            $invalidProperties[] = "'paypay' can't be null";
        }
        if ($this->container['card'] === null) {
            $invalidProperties[] = "'card' can't be null";
        }
        if ($this->container['applePay'] === null) {
            $invalidProperties[] = "'applePay' can't be null";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets object
     *
     * @return string|null
     */
    public function getObject(): ?string
    {
        return $this->container['object'];
    }

    /**
     * Sets object
     *
     * @param string|null $object object
     *
     * @return self
     */
    public function setObject(?string $object): self
    {
        if (is_null($object)) {
            throw new \InvalidArgumentException('non-nullable object cannot be null');
        }
        $allowedValues = $this->getObjectAllowableValues();
        if (! in_array($object, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'object', must be one of '%s'",
                    $object,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['object'] = $object;

        return $this;
    }

    /**
     * Gets id
     *
     * @return string
     */
    public function getId(): string
    {
        if ($this->container['id'] === null) {
            throw new \LogicException('Property "id" is required but has not been set.');
        }

        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id 支払い方法設定 ID
     *
     * @return self
     */
    public function setId(string $id): self
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets livemode
     *
     * @return bool
     */
    public function getLivemode(): bool
    {
        if ($this->container['livemode'] === null) {
            throw new \LogicException('Property "livemode" is required but has not been set.');
        }

        return $this->container['livemode'];
    }

    /**
     * Sets livemode
     *
     * @param bool $livemode 本番環境かどうか
     *
     * @return self
     */
    public function setLivemode(bool $livemode): self
    {
        if (is_null($livemode)) {
            throw new \InvalidArgumentException('non-nullable livemode cannot be null');
        }
        $this->container['livemode'] = $livemode;

        return $this;
    }

    /**
     * Gets active
     *
     * @return bool
     */
    public function getActive(): bool
    {
        if ($this->container['active'] === null) {
            throw new \LogicException('Property "active" is required but has not been set.');
        }

        return $this->container['active'];
    }

    /**
     * Sets active
     *
     * @param bool $active 設定が有効かどうか
     *
     * @return self
     */
    public function setActive(bool $active): self
    {
        if (is_null($active)) {
            throw new \InvalidArgumentException('non-nullable active cannot be null');
        }
        $this->container['active'] = $active;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName(): ?string
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name name
     *
     * @return self
     */
    public function setName(?string $name): self
    {
        if (is_null($name)) {
            array_push($this->openAPINullablesSetToNull, 'name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('name', $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets paypay
     *
     * @return \PAYJPV2\Model\PaymentMethodConfigurationSettingResponse
     */
    public function getPaypay(): \PAYJPV2\Model\PaymentMethodConfigurationSettingResponse
    {
        if ($this->container['paypay'] === null) {
            throw new \LogicException('Property "paypay" is required but has not been set.');
        }

        return $this->container['paypay'];
    }

    /**
     * Sets paypay
     *
     * @param \PAYJPV2\Model\PaymentMethodConfigurationSettingResponse $paypay PayPay の設定
     *
     * @return self
     */
    public function setPaypay(\PAYJPV2\Model\PaymentMethodConfigurationSettingResponse $paypay): self
    {
        if (is_null($paypay)) {
            throw new \InvalidArgumentException('non-nullable paypay cannot be null');
        }
        $this->container['paypay'] = $paypay;

        return $this;
    }

    /**
     * Gets card
     *
     * @return \PAYJPV2\Model\PaymentMethodConfigurationSettingResponse
     */
    public function getCard(): \PAYJPV2\Model\PaymentMethodConfigurationSettingResponse
    {
        if ($this->container['card'] === null) {
            throw new \LogicException('Property "card" is required but has not been set.');
        }

        return $this->container['card'];
    }

    /**
     * Sets card
     *
     * @param \PAYJPV2\Model\PaymentMethodConfigurationSettingResponse $card カードの設定
     *
     * @return self
     */
    public function setCard(\PAYJPV2\Model\PaymentMethodConfigurationSettingResponse $card): self
    {
        if (is_null($card)) {
            throw new \InvalidArgumentException('non-nullable card cannot be null');
        }
        $this->container['card'] = $card;

        return $this;
    }

    /**
     * Gets applePay
     *
     * @return \PAYJPV2\Model\PaymentMethodConfigurationSettingResponse
     */
    public function getApplePay(): \PAYJPV2\Model\PaymentMethodConfigurationSettingResponse
    {
        if ($this->container['applePay'] === null) {
            throw new \LogicException('Property "applePay" is required but has not been set.');
        }

        return $this->container['applePay'];
    }

    /**
     * Sets applePay
     *
     * @param \PAYJPV2\Model\PaymentMethodConfigurationSettingResponse $applePay Apple Pay の設定
     *
     * @return self
     */
    public function setApplePay(\PAYJPV2\Model\PaymentMethodConfigurationSettingResponse $applePay): self
    {
        if (is_null($applePay)) {
            throw new \InvalidArgumentException('non-nullable applePay cannot be null');
        }
        $this->container['applePay'] = $applePay;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int $offset Offset
     *
     * @return bool
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
