<?php

/**
 * PaymentFlowCreateRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  PAYJPV2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PAY.JP API v2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PAYJPV2\Model;

use ArrayAccess;
use PAYJPV2\ObjectSerializer;

/**
 * PaymentFlowCreateRequest Class Doc Comment
 *
 * @category Class
 * @package  PAYJPV2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PaymentFlowCreateRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'PaymentFlowCreateRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'amount' => 'int',
        'customerId' => 'string',
        'paymentMethodId' => 'string',
        'paymentMethodOptions' => '\PAYJPV2\Model\PaymentFlowPaymentMethodOptionsRequest',
        'paymentMethodTypes' => '\PAYJPV2\Model\PaymentMethodTypes[]',
        'currency' => '\PAYJPV2\Model\Currency',
        'captureMethod' => '\PAYJPV2\Model\CaptureMethod',
        'confirm' => 'bool',
        'returnUrl' => 'string',
        'description' => 'string',
        'metadata' => 'array<string,\PAYJPV2\Model\MetadataValue>',
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'amount' => null,
        'customerId' => null,
        'paymentMethodId' => null,
        'paymentMethodOptions' => null,
        'paymentMethodTypes' => null,
        'currency' => null,
        'captureMethod' => null,
        'confirm' => null,
        'returnUrl' => null,
        'description' => null,
        'metadata' => null,
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var bool[]
      */
    protected static array $openAPINullables = [
        'amount' => false,
        'customerId' => false,
        'paymentMethodId' => false,
        'paymentMethodOptions' => false,
        'paymentMethodTypes' => false,
        'currency' => false,
        'captureMethod' => false,
        'confirm' => false,
        'returnUrl' => false,
        'description' => false,
        'metadata' => false,
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var bool[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return bool[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param bool[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'amount' => 'amount',
        'customerId' => 'customer_id',
        'paymentMethodId' => 'payment_method_id',
        'paymentMethodOptions' => 'payment_method_options',
        'paymentMethodTypes' => 'payment_method_types',
        'currency' => 'currency',
        'captureMethod' => 'capture_method',
        'confirm' => 'confirm',
        'returnUrl' => 'return_url',
        'description' => 'description',
        'metadata' => 'metadata',
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'amount' => 'setAmount',
        'customerId' => 'setCustomerId',
        'paymentMethodId' => 'setPaymentMethodId',
        'paymentMethodOptions' => 'setPaymentMethodOptions',
        'paymentMethodTypes' => 'setPaymentMethodTypes',
        'currency' => 'setCurrency',
        'captureMethod' => 'setCaptureMethod',
        'confirm' => 'setConfirm',
        'returnUrl' => 'setReturnUrl',
        'description' => 'setDescription',
        'metadata' => 'setMetadata',
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'amount' => 'getAmount',
        'customerId' => 'getCustomerId',
        'paymentMethodId' => 'getPaymentMethodId',
        'paymentMethodOptions' => 'getPaymentMethodOptions',
        'paymentMethodTypes' => 'getPaymentMethodTypes',
        'currency' => 'getCurrency',
        'captureMethod' => 'getCaptureMethod',
        'confirm' => 'getConfirm',
        'returnUrl' => 'getReturnUrl',
        'description' => 'getDescription',
        'metadata' => 'getMetadata',
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('amount', $data ?? [], null);
        $this->setIfExists('customerId', $data ?? [], null);
        $this->setIfExists('paymentMethodId', $data ?? [], null);
        $this->setIfExists('paymentMethodOptions', $data ?? [], null);
        $this->setIfExists('paymentMethodTypes', $data ?? [], null);
        $this->setIfExists('currency', $data ?? [], null);
        $this->setIfExists('captureMethod', $data ?? [], null);
        $this->setIfExists('confirm', $data ?? [], false);
        $this->setIfExists('returnUrl', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('metadata', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['amount'] === null) {
            $invalidProperties[] = "'amount' can't be null";
        }
        if (($this->container['amount'] > 9999999)) {
            $invalidProperties[] = "invalid value for 'amount', must be smaller than or equal to 9999999.";
        }

        if (($this->container['amount'] < 50)) {
            $invalidProperties[] = "invalid value for 'amount', must be bigger than or equal to 50.";
        }

        if ($this->container['currency'] === null) {
            $invalidProperties[] = "'currency' can't be null";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets amount
     *
     * @return int
     */
    public function getAmount(): int
    {
        if ($this->container['amount'] === null) {
            throw new \LogicException('Property "amount" is required but has not been set.');
        }

        return $this->container['amount'];
    }

    /**
     * Sets amount
     *
     * @param int $amount 支払い予定の金額。50円以上9,999,999円以下である必要があります。
     *
     * @return self
     */
    public function setAmount(int $amount): self
    {
        if (is_null($amount)) {
            throw new \InvalidArgumentException('non-nullable amount cannot be null');
        }

        if (($amount > 9999999)) {
            throw new \InvalidArgumentException('invalid value for $amount when calling PaymentFlowCreateRequest., must be smaller than or equal to 9999999.');
        }
        if (($amount < 50)) {
            throw new \InvalidArgumentException('invalid value for $amount when calling PaymentFlowCreateRequest., must be bigger than or equal to 50.');
        }

        $this->container['amount'] = $amount;

        return $this;
    }

    /**
     * Gets customerId
     *
     * @return string|null
     */
    public function getCustomerId(): ?string
    {
        return $this->container['customerId'];
    }

    /**
     * Sets customerId
     *
     * @param string|null $customerId このPaymentFlowに関連付ける顧客のID
     *
     * @return self
     */
    public function setCustomerId(?string $customerId): self
    {
        if (is_null($customerId)) {
            throw new \InvalidArgumentException('non-nullable customerId cannot be null');
        }
        $this->container['customerId'] = $customerId;

        return $this;
    }

    /**
     * Gets paymentMethodId
     *
     * @return string|null
     */
    public function getPaymentMethodId(): ?string
    {
        return $this->container['paymentMethodId'];
    }

    /**
     * Sets paymentMethodId
     *
     * @param string|null $paymentMethodId 支払い方法ID。customer_idの指定が必須です。Customerが所持するPaymentMethodのみ指定できます。payment_method_idを指定せず、Customerにdefault_payment_method_idが設定されている場合はそちらが自動でセットされます。
     *
     * @return self
     */
    public function setPaymentMethodId(?string $paymentMethodId): self
    {
        if (is_null($paymentMethodId)) {
            throw new \InvalidArgumentException('non-nullable paymentMethodId cannot be null');
        }
        $this->container['paymentMethodId'] = $paymentMethodId;

        return $this;
    }

    /**
     * Gets paymentMethodOptions
     *
     * @return \PAYJPV2\Model\PaymentFlowPaymentMethodOptionsRequest|null
     */
    public function getPaymentMethodOptions(): ?\PAYJPV2\Model\PaymentFlowPaymentMethodOptionsRequest
    {
        return $this->container['paymentMethodOptions'];
    }

    /**
     * Sets paymentMethodOptions
     *
     * @param \PAYJPV2\Model\PaymentFlowPaymentMethodOptionsRequest|null $paymentMethodOptions このPaymentFlow固有の支払い方法の設定
     *
     * @return self
     */
    public function setPaymentMethodOptions(?\PAYJPV2\Model\PaymentFlowPaymentMethodOptionsRequest $paymentMethodOptions): self
    {
        if (is_null($paymentMethodOptions)) {
            throw new \InvalidArgumentException('non-nullable paymentMethodOptions cannot be null');
        }
        $this->container['paymentMethodOptions'] = $paymentMethodOptions;

        return $this;
    }

    /**
     * Gets paymentMethodTypes
     *
     * @return \PAYJPV2\Model\PaymentMethodTypes[]|null
     */
    public function getPaymentMethodTypes(): ?array
    {
        return $this->container['paymentMethodTypes'];
    }

    /**
     * Sets paymentMethodTypes
     *
     * @param \PAYJPV2\Model\PaymentMethodTypes[]|null $paymentMethodTypes このPaymentFlowで使用できる支払い方法の種類のリスト。 指定しない場合は、PAY.JPは支払い方法の設定から利用可能な支払い方法を動的に表示します。
     *
     * @return self
     */
    public function setPaymentMethodTypes(?array $paymentMethodTypes): self
    {
        if (is_null($paymentMethodTypes)) {
            throw new \InvalidArgumentException('non-nullable paymentMethodTypes cannot be null');
        }
        $this->container['paymentMethodTypes'] = $paymentMethodTypes;

        return $this;
    }

    /**
     * Gets currency
     *
     * @return \PAYJPV2\Model\Currency
     */
    public function getCurrency(): \PAYJPV2\Model\Currency
    {
        if ($this->container['currency'] === null) {
            throw new \LogicException('Property "currency" is required but has not been set.');
        }

        return $this->container['currency'];
    }

    /**
     * Sets currency
     *
     * @param \PAYJPV2\Model\Currency $currency 価格の通貨。現在は `jpy` のみサポートしています。
     *
     * @return self
     */
    public function setCurrency(\PAYJPV2\Model\Currency $currency): self
    {
        if (is_null($currency)) {
            throw new \InvalidArgumentException('non-nullable currency cannot be null');
        }
        $this->container['currency'] = $currency;

        return $this;
    }

    /**
     * Gets captureMethod
     *
     * @return \PAYJPV2\Model\CaptureMethod|null
     */
    public function getCaptureMethod(): ?\PAYJPV2\Model\CaptureMethod
    {
        return $this->container['captureMethod'];
    }

    /**
     * Sets captureMethod
     *
     * @param \PAYJPV2\Model\CaptureMethod|null $captureMethod 支払いの確定方法を指定します。  | 指定できる値 | |:---| | **automatic**: (デフォルト) 顧客が支払いを承認すると、自動的に確定させます。 | | **manual**: 顧客が支払いを承認すると一旦確定を保留し、後で Capture API を使用して確定します。（すべての支払い方法がこれをサポートしているわけではありません）。 |
     *
     * @return self
     */
    public function setCaptureMethod(?\PAYJPV2\Model\CaptureMethod $captureMethod): self
    {
        if (is_null($captureMethod)) {
            throw new \InvalidArgumentException('non-nullable captureMethod cannot be null');
        }
        $this->container['captureMethod'] = $captureMethod;

        return $this;
    }

    /**
     * Gets confirm
     *
     * @return bool|null
     */
    public function getConfirm(): ?bool
    {
        return $this->container['confirm'];
    }

    /**
     * Sets confirm
     *
     * @param bool|null $confirm 「true」に設定すると、このPaymentFlowを直ちに確定しようと試みます。
     *
     * @return self
     */
    public function setConfirm(?bool $confirm): self
    {
        if (is_null($confirm)) {
            throw new \InvalidArgumentException('non-nullable confirm cannot be null');
        }
        $this->container['confirm'] = $confirm;

        return $this;
    }

    /**
     * Gets returnUrl
     *
     * @return string|null
     */
    public function getReturnUrl(): ?string
    {
        return $this->container['returnUrl'];
    }

    /**
     * Sets returnUrl
     *
     * @param string|null $returnUrl 顧客が支払いを完了後かキャンセルした後にリダイレクトされるURL。アプリにリダイレクトしたい場合は URI Scheme を指定できます。confirm=trueの場合のみ指定できます。
     *
     * @return self
     */
    public function setReturnUrl(?string $returnUrl): self
    {
        if (is_null($returnUrl)) {
            throw new \InvalidArgumentException('non-nullable returnUrl cannot be null');
        }
        $this->container['returnUrl'] = $returnUrl;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription(): ?string
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description オブジェクトにセットする任意の文字列。ユーザーには表示されません。
     *
     * @return self
     */
    public function setDescription(?string $description): self
    {
        if (is_null($description)) {
            throw new \InvalidArgumentException('non-nullable description cannot be null');
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets metadata
     *
     * @return array<string,\PAYJPV2\Model\MetadataValue>|null
     */
    public function getMetadata(): ?array
    {
        return $this->container['metadata'];
    }

    /**
     * Sets metadata
     *
     * @param array<string,\PAYJPV2\Model\MetadataValue>|null $metadata キーバリューの任意のデータを格納できます。<a href=\"https://docs.pay.jp/v2/metadata\">詳細はメタデータのドキュメントを参照してください。</a>
     *
     * @return self
     */
    public function setMetadata(?array $metadata): self
    {
        if (is_null($metadata)) {
            throw new \InvalidArgumentException('non-nullable metadata cannot be null');
        }
        $this->container['metadata'] = $metadata;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int $offset Offset
     *
     * @return bool
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
