<?php
/**
 * PaymentTransactionType
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  PAYJPV2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PAY.JP API v2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PAYJPV2\Model;
use \PAYJPV2\ObjectSerializer;

/**
 * PaymentTransactionType Class Doc Comment
 *
 * @category Class
 * @package  PAYJPV2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PaymentTransactionType
{
    /**
     * Possible values of this enum
     */
    public const PAYMENT = 'payment';

    public const REFUND = 'refund';

    public const CHARGEBACK = 'chargeback';

    public const CHARGEBACK_CANCEL = 'chargeback_cancel';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PAYMENT,
            self::REFUND,
            self::CHARGEBACK,
            self::CHARGEBACK_CANCEL
        ];
    }
}


