<?php

/**
 * SetupFlowResponse
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  PAYJPV2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PAY.JP API v2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PAYJPV2\Model;

use ArrayAccess;
use PAYJPV2\ObjectSerializer;

/**
 * SetupFlowResponse Class Doc Comment
 *
 * @category Class
 * @package  PAYJPV2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class SetupFlowResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'SetupFlowResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'object' => 'string',
        'id' => 'string',
        'livemode' => 'bool',
        'clientSecret' => 'string',
        'customerId' => 'string',
        'description' => 'string',
        'metadata' => 'array<string,\PAYJPV2\Model\MetadataValue>',
        'paymentMethodId' => 'string',
        'paymentMethodOptions' => 'array<string,mixed>',
        'paymentMethodTypes' => '\PAYJPV2\Model\PaymentMethodTypes[]',
        'status' => '\PAYJPV2\Model\SetupFlowStatus',
        'nextAction' => 'array<string,mixed>',
        'returnUrl' => 'string',
        'lastSetupError' => 'array<string,mixed>',
        'cancellationReason' => '\PAYJPV2\Model\SetupFlowCancellationReason',
        'createdAt' => '\DateTime',
        'updatedAt' => '\DateTime',
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'object' => null,
        'id' => null,
        'livemode' => null,
        'clientSecret' => null,
        'customerId' => null,
        'description' => null,
        'metadata' => null,
        'paymentMethodId' => null,
        'paymentMethodOptions' => null,
        'paymentMethodTypes' => null,
        'status' => null,
        'nextAction' => null,
        'returnUrl' => null,
        'lastSetupError' => null,
        'cancellationReason' => null,
        'createdAt' => 'date-time',
        'updatedAt' => 'date-time',
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var bool[]
      */
    protected static array $openAPINullables = [
        'object' => false,
        'id' => false,
        'livemode' => false,
        'clientSecret' => false,
        'customerId' => true,
        'description' => true,
        'metadata' => false,
        'paymentMethodId' => true,
        'paymentMethodOptions' => true,
        'paymentMethodTypes' => false,
        'status' => false,
        'nextAction' => true,
        'returnUrl' => true,
        'lastSetupError' => true,
        'cancellationReason' => true,
        'createdAt' => false,
        'updatedAt' => false,
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var bool[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return bool[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param bool[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'object' => 'object',
        'id' => 'id',
        'livemode' => 'livemode',
        'clientSecret' => 'client_secret',
        'customerId' => 'customer_id',
        'description' => 'description',
        'metadata' => 'metadata',
        'paymentMethodId' => 'payment_method_id',
        'paymentMethodOptions' => 'payment_method_options',
        'paymentMethodTypes' => 'payment_method_types',
        'status' => 'status',
        'nextAction' => 'next_action',
        'returnUrl' => 'return_url',
        'lastSetupError' => 'last_setup_error',
        'cancellationReason' => 'cancellation_reason',
        'createdAt' => 'created_at',
        'updatedAt' => 'updated_at',
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'object' => 'setObject',
        'id' => 'setId',
        'livemode' => 'setLivemode',
        'clientSecret' => 'setClientSecret',
        'customerId' => 'setCustomerId',
        'description' => 'setDescription',
        'metadata' => 'setMetadata',
        'paymentMethodId' => 'setPaymentMethodId',
        'paymentMethodOptions' => 'setPaymentMethodOptions',
        'paymentMethodTypes' => 'setPaymentMethodTypes',
        'status' => 'setStatus',
        'nextAction' => 'setNextAction',
        'returnUrl' => 'setReturnUrl',
        'lastSetupError' => 'setLastSetupError',
        'cancellationReason' => 'setCancellationReason',
        'createdAt' => 'setCreatedAt',
        'updatedAt' => 'setUpdatedAt',
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'object' => 'getObject',
        'id' => 'getId',
        'livemode' => 'getLivemode',
        'clientSecret' => 'getClientSecret',
        'customerId' => 'getCustomerId',
        'description' => 'getDescription',
        'metadata' => 'getMetadata',
        'paymentMethodId' => 'getPaymentMethodId',
        'paymentMethodOptions' => 'getPaymentMethodOptions',
        'paymentMethodTypes' => 'getPaymentMethodTypes',
        'status' => 'getStatus',
        'nextAction' => 'getNextAction',
        'returnUrl' => 'getReturnUrl',
        'lastSetupError' => 'getLastSetupError',
        'cancellationReason' => 'getCancellationReason',
        'createdAt' => 'getCreatedAt',
        'updatedAt' => 'getUpdatedAt',
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const OBJECT_SETUP_FLOW = 'setup_flow';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getObjectAllowableValues()
    {
        return [
            self::OBJECT_SETUP_FLOW,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('object', $data ?? [], 'setup_flow');
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('livemode', $data ?? [], null);
        $this->setIfExists('clientSecret', $data ?? [], null);
        $this->setIfExists('customerId', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('metadata', $data ?? [], null);
        $this->setIfExists('paymentMethodId', $data ?? [], null);
        $this->setIfExists('paymentMethodOptions', $data ?? [], null);
        $this->setIfExists('paymentMethodTypes', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('nextAction', $data ?? [], null);
        $this->setIfExists('returnUrl', $data ?? [], null);
        $this->setIfExists('lastSetupError', $data ?? [], null);
        $this->setIfExists('cancellationReason', $data ?? [], null);
        $this->setIfExists('createdAt', $data ?? [], null);
        $this->setIfExists('updatedAt', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getObjectAllowableValues();
        if (! is_null($this->container['object']) && ! in_array($this->container['object'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'object', must be one of '%s'",
                $this->container['object'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['livemode'] === null) {
            $invalidProperties[] = "'livemode' can't be null";
        }
        if ($this->container['clientSecret'] === null) {
            $invalidProperties[] = "'clientSecret' can't be null";
        }
        if ($this->container['customerId'] === null) {
            $invalidProperties[] = "'customerId' can't be null";
        }
        if ($this->container['description'] === null) {
            $invalidProperties[] = "'description' can't be null";
        }
        if ($this->container['metadata'] === null) {
            $invalidProperties[] = "'metadata' can't be null";
        }
        if ($this->container['paymentMethodId'] === null) {
            $invalidProperties[] = "'paymentMethodId' can't be null";
        }
        if ($this->container['paymentMethodOptions'] === null) {
            $invalidProperties[] = "'paymentMethodOptions' can't be null";
        }
        if ($this->container['paymentMethodTypes'] === null) {
            $invalidProperties[] = "'paymentMethodTypes' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        if ($this->container['nextAction'] === null) {
            $invalidProperties[] = "'nextAction' can't be null";
        }
        if ($this->container['returnUrl'] === null) {
            $invalidProperties[] = "'returnUrl' can't be null";
        }
        if ($this->container['lastSetupError'] === null) {
            $invalidProperties[] = "'lastSetupError' can't be null";
        }
        if ($this->container['cancellationReason'] === null) {
            $invalidProperties[] = "'cancellationReason' can't be null";
        }
        if ($this->container['createdAt'] === null) {
            $invalidProperties[] = "'createdAt' can't be null";
        }
        if ($this->container['updatedAt'] === null) {
            $invalidProperties[] = "'updatedAt' can't be null";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets object
     *
     * @return string|null
     */
    public function getObject(): ?string
    {
        return $this->container['object'];
    }

    /**
     * Sets object
     *
     * @param string|null $object object
     *
     * @return self
     */
    public function setObject(?string $object): self
    {
        if (is_null($object)) {
            throw new \InvalidArgumentException('non-nullable object cannot be null');
        }
        $allowedValues = $this->getObjectAllowableValues();
        if (! in_array($object, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'object', must be one of '%s'",
                    $object,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['object'] = $object;

        return $this;
    }

    /**
     * Gets id
     *
     * @return string
     */
    public function getId(): string
    {
        if ($this->container['id'] === null) {
            throw new \LogicException('Property "id" is required but has not been set.');
        }

        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id ID
     *
     * @return self
     */
    public function setId(string $id): self
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets livemode
     *
     * @return bool
     */
    public function getLivemode(): bool
    {
        if ($this->container['livemode'] === null) {
            throw new \LogicException('Property "livemode" is required but has not been set.');
        }

        return $this->container['livemode'];
    }

    /**
     * Sets livemode
     *
     * @param bool $livemode 本番環境かどうか
     *
     * @return self
     */
    public function setLivemode(bool $livemode): self
    {
        if (is_null($livemode)) {
            throw new \InvalidArgumentException('non-nullable livemode cannot be null');
        }
        $this->container['livemode'] = $livemode;

        return $this;
    }

    /**
     * Gets clientSecret
     *
     * @return string
     */
    public function getClientSecret(): string
    {
        if ($this->container['clientSecret'] === null) {
            throw new \LogicException('Property "clientSecret" is required but has not been set.');
        }

        return $this->container['clientSecret'];
    }

    /**
     * Sets clientSecret
     *
     * @param string $clientSecret この SetupFlow のクライアントシークレットです。フロントエンドで公開鍵と合わせて使用し、SetupFlow の取得や支払い方法の登録処理を行います。**この値はこの SetupFlow を利用する顧客以外へ公開しないでください。
     *
     * @return self
     */
    public function setClientSecret(string $clientSecret): self
    {
        if (is_null($clientSecret)) {
            throw new \InvalidArgumentException('non-nullable clientSecret cannot be null');
        }
        $this->container['clientSecret'] = $clientSecret;

        return $this;
    }

    /**
     * Gets customerId
     *
     * @return string|null
     */
    public function getCustomerId(): ?string
    {
        return $this->container['customerId'];
    }

    /**
     * Sets customerId
     *
     * @param string|null $customerId customerId
     *
     * @return self
     */
    public function setCustomerId(?string $customerId): self
    {
        if (is_null($customerId)) {
            array_push($this->openAPINullablesSetToNull, 'customerId');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('customerId', $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['customerId'] = $customerId;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription(): ?string
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description description
     *
     * @return self
     */
    public function setDescription(?string $description): self
    {
        if (is_null($description)) {
            array_push($this->openAPINullablesSetToNull, 'description');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('description', $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets metadata
     *
     * @return array<string,\PAYJPV2\Model\MetadataValue>
     */
    public function getMetadata(): array
    {
        if ($this->container['metadata'] === null) {
            throw new \LogicException('Property "metadata" is required but has not been set.');
        }

        return $this->container['metadata'];
    }

    /**
     * Sets metadata
     *
     * @param array<string,\PAYJPV2\Model\MetadataValue> $metadata メタデータ
     *
     * @return self
     */
    public function setMetadata(array $metadata): self
    {
        if (is_null($metadata)) {
            throw new \InvalidArgumentException('non-nullable metadata cannot be null');
        }
        $this->container['metadata'] = $metadata;

        return $this;
    }

    /**
     * Gets paymentMethodId
     *
     * @return string|null
     */
    public function getPaymentMethodId(): ?string
    {
        return $this->container['paymentMethodId'];
    }

    /**
     * Sets paymentMethodId
     *
     * @param string|null $paymentMethodId paymentMethodId
     *
     * @return self
     */
    public function setPaymentMethodId(?string $paymentMethodId): self
    {
        if (is_null($paymentMethodId)) {
            array_push($this->openAPINullablesSetToNull, 'paymentMethodId');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('paymentMethodId', $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['paymentMethodId'] = $paymentMethodId;

        return $this;
    }

    /**
     * Gets paymentMethodOptions
     *
     * @return array<string,mixed>|null
     */
    public function getPaymentMethodOptions(): ?array
    {
        return $this->container['paymentMethodOptions'];
    }

    /**
     * Sets paymentMethodOptions
     *
     * @param array<string,mixed>|null $paymentMethodOptions paymentMethodOptions
     *
     * @return self
     */
    public function setPaymentMethodOptions(?array $paymentMethodOptions): self
    {
        if (is_null($paymentMethodOptions)) {
            array_push($this->openAPINullablesSetToNull, 'paymentMethodOptions');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('paymentMethodOptions', $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['paymentMethodOptions'] = $paymentMethodOptions;

        return $this;
    }

    /**
     * Gets paymentMethodTypes
     *
     * @return \PAYJPV2\Model\PaymentMethodTypes[]
     */
    public function getPaymentMethodTypes(): array
    {
        if ($this->container['paymentMethodTypes'] === null) {
            throw new \LogicException('Property "paymentMethodTypes" is required but has not been set.');
        }

        return $this->container['paymentMethodTypes'];
    }

    /**
     * Sets paymentMethodTypes
     *
     * @param \PAYJPV2\Model\PaymentMethodTypes[] $paymentMethodTypes この SetupFlow で使用できる支払い方法の種類のリスト
     *
     * @return self
     */
    public function setPaymentMethodTypes(array $paymentMethodTypes): self
    {
        if (is_null($paymentMethodTypes)) {
            throw new \InvalidArgumentException('non-nullable paymentMethodTypes cannot be null');
        }
        $this->container['paymentMethodTypes'] = $paymentMethodTypes;

        return $this;
    }

    /**
     * Gets status
     *
     * @return \PAYJPV2\Model\SetupFlowStatus
     */
    public function getStatus(): \PAYJPV2\Model\SetupFlowStatus
    {
        if ($this->container['status'] === null) {
            throw new \LogicException('Property "status" is required but has not been set.');
        }

        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param \PAYJPV2\Model\SetupFlowStatus $status この SetupFlow のステータスです。<a href=\"https://docs.pay.jp/v2/guide/payments/setupflow#setup-flow-%E3%81%AE%E3%82%B9%E3%83%86%E3%83%BC%E3%82%BF%E3%82%B9\" target=\"_blank\">ステータスの詳細についてはこちらをご覧ください。</a>  | 値 | |:---| | **requires_payment_method**: 支払い方法が必要です。 | | **requires_confirmation**: 確認が必要です。 | | **requires_action**: 顧客のアクションが必要です。 | | **processing**: 処理中です。 | | **succeeded**: 成功しました。 | | **canceled**: キャンセルされました。 |
     *
     * @return self
     */
    public function setStatus(\PAYJPV2\Model\SetupFlowStatus $status): self
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets nextAction
     *
     * @return array<string,mixed>|null
     */
    public function getNextAction(): ?array
    {
        return $this->container['nextAction'];
    }

    /**
     * Sets nextAction
     *
     * @param array<string,mixed>|null $nextAction nextAction
     *
     * @return self
     */
    public function setNextAction(?array $nextAction): self
    {
        if (is_null($nextAction)) {
            array_push($this->openAPINullablesSetToNull, 'nextAction');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('nextAction', $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['nextAction'] = $nextAction;

        return $this;
    }

    /**
     * Gets returnUrl
     *
     * @return string|null
     */
    public function getReturnUrl(): ?string
    {
        return $this->container['returnUrl'];
    }

    /**
     * Sets returnUrl
     *
     * @param string|null $returnUrl returnUrl
     *
     * @return self
     */
    public function setReturnUrl(?string $returnUrl): self
    {
        if (is_null($returnUrl)) {
            array_push($this->openAPINullablesSetToNull, 'returnUrl');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('returnUrl', $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['returnUrl'] = $returnUrl;

        return $this;
    }

    /**
     * Gets lastSetupError
     *
     * @return array<string,mixed>|null
     */
    public function getLastSetupError(): ?array
    {
        return $this->container['lastSetupError'];
    }

    /**
     * Sets lastSetupError
     *
     * @param array<string,mixed>|null $lastSetupError lastSetupError
     *
     * @return self
     */
    public function setLastSetupError(?array $lastSetupError): self
    {
        if (is_null($lastSetupError)) {
            array_push($this->openAPINullablesSetToNull, 'lastSetupError');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('lastSetupError', $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['lastSetupError'] = $lastSetupError;

        return $this;
    }

    /**
     * Gets cancellationReason
     *
     * @return \PAYJPV2\Model\SetupFlowCancellationReason|null
     */
    public function getCancellationReason(): ?\PAYJPV2\Model\SetupFlowCancellationReason
    {
        return $this->container['cancellationReason'];
    }

    /**
     * Sets cancellationReason
     *
     * @param \PAYJPV2\Model\SetupFlowCancellationReason|null $cancellationReason cancellationReason
     *
     * @return self
     */
    public function setCancellationReason(?\PAYJPV2\Model\SetupFlowCancellationReason $cancellationReason): self
    {
        if (is_null($cancellationReason)) {
            array_push($this->openAPINullablesSetToNull, 'cancellationReason');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('cancellationReason', $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['cancellationReason'] = $cancellationReason;

        return $this;
    }

    /**
     * Gets createdAt
     *
     * @return \DateTime
     */
    public function getCreatedAt(): \DateTime
    {
        if ($this->container['createdAt'] === null) {
            throw new \LogicException('Property "createdAt" is required but has not been set.');
        }

        return $this->container['createdAt'];
    }

    /**
     * Sets createdAt
     *
     * @param \DateTime $createdAt 作成日時 (UTC, ISO 8601 形式)
     *
     * @return self
     */
    public function setCreatedAt(\DateTime $createdAt): self
    {
        if (is_null($createdAt)) {
            throw new \InvalidArgumentException('non-nullable createdAt cannot be null');
        }
        $this->container['createdAt'] = $createdAt;

        return $this;
    }

    /**
     * Gets updatedAt
     *
     * @return \DateTime
     */
    public function getUpdatedAt(): \DateTime
    {
        if ($this->container['updatedAt'] === null) {
            throw new \LogicException('Property "updatedAt" is required but has not been set.');
        }

        return $this->container['updatedAt'];
    }

    /**
     * Sets updatedAt
     *
     * @param \DateTime $updatedAt 更新日時 (UTC, ISO 8601 形式)
     *
     * @return self
     */
    public function setUpdatedAt(\DateTime $updatedAt): self
    {
        if (is_null($updatedAt)) {
            throw new \InvalidArgumentException('non-nullable updatedAt cannot be null');
        }
        $this->container['updatedAt'] = $updatedAt;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int $offset Offset
     *
     * @return bool
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
