<?php

/**
 * StatementSubject
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  PAYJPV2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PAY.JP API v2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PAYJPV2\Model;

/**
 * StatementSubject Class Doc Comment
 *
 * @category Class
 * @description StatementItemの科目  分類の増減は会計・経理の目線で行われる。 経理上取り扱いが違う数字は別のsubjectになる、もしくはその他の情報を組み合わせて区別できる必要がある。
 * @package  PAYJPV2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
enum StatementSubject: string
{
    case GROSS_SALES = 'gross_sales';
    case FEE = 'fee';
    case PLATFORM_FEE = 'platform_fee';
    case GROSS_REFUND = 'gross_refund';
    case REFUND_FEE_OFFSET = 'refund_fee_offset';
    case REFUND_PLATFORM_FEE_OFFSET = 'refund_platform_fee_offset';
    case CHARGEBACK = 'chargeback';
    case CHARGEBACK_FEE_OFFSET = 'chargeback_fee_offset';
    case CHARGEBACK_PLATFORM_FEE_OFFSET = 'chargeback_platform_fee_offset';
    case PROPLAN = 'proplan';
    case PLAN_FEE = 'plan_fee';
    case FORFEIT = 'forfeit';
    case REALLOCATION = 'reallocation';
    case YELL_BANK_COLLECTION = 'yell_bank_collection';
    case PYB_EARLY_DEPOSIT_SERVICE_FEE = 'pyb_early_deposit_service_fee';
    case TRANSFER_FEE = 'transfer_fee';
    case OTHER = 'other';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues(): array
    {
        return array_column(self::cases(), 'value');
    }
}
